import {actor,get,put,db,uid,now} from '../../../lib/lab';
import {emailStatus,sendMail,sendTestEmail} from '../../../lib/email';
import {validEmail} from '../../../lib/imports';
const hash=async(s:string)=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))).toString('hex');
export async function GET(){try{const u=await actor();const profile=await get('profile:'+u.id);const deliveries=u.role==='admin'?(await db().prepare('SELECT * FROM deliveries ORDER BY updated DESC LIMIT 100').all()).results:[];return Response.json({...(await emailStatus()),profile:profile||{email:u.email,emailVerified:false,courses:['UP 406','UP 417']},deliveries});}catch(e:any){return Response.json({error:String(e.message).includes('D1_')?'Email settings are temporarily unavailable. Please reload.':e.message},{status:403});}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)throw new Error('Invalid origin.');const u=await actor(),b:any=await req.json(),id='email-challenge:'+u.id,old=await get(id),profile=await get('profile:'+u.id);if(b.action==='test'){if(u.role!=='admin')throw new Error('Lecturer access required.');const to=String(b.email||'').trim().toLowerCase();if(!validEmail(to))throw new Error('Enter an email address to send the test to.');await sendTestEmail(to);return Response.json({ok:true,message:'Test email sent to '+to+'. Check that inbox (and Spam).'});}if(b.action==='preferences'){const notifications:any={};for(const key of ['classes','deadlines','marks','roomChanges','announcements']){const v=b.notifications?.[key];if(v!==undefined&&typeof v!=='boolean')throw new Error('Invalid notification preference.');notifications[key]=v!==false;}await put('profile','profile:'+u.id,{...(profile||{}),owner:u.id,email:profile?.email||u.email,courses:profile?.courses||['UP 406','UP 417'],notifications},profile?.revision);return Response.json({ok:true});}if(b.action==='request'){
const email=String(b.email||'').trim().toLowerCase();if(!validEmail(email))throw new Error('Enter an email address you can open.');if(old&&Date.now()-Date.parse(old.sent)<60000)throw new Error('Wait one minute before requesting another code.');const sameDay=old?.sent?.slice(0,10)===now().slice(0,10);if(sameDay&&old.requests>=5)throw new Error('You have requested five codes today. Try again tomorrow.');const code=String(100000+crypto.getRandomValues(new Uint32Array(1))[0]%900000),salt=uid();
await sendMail(email,'Verify your student reminder email',`Hello ${u.name},\n\nYour ArchPlaza verification code is ${code}.\nIt expires in 10 minutes. Do not share this code.\n\nIf you did not request this, ignore this email.`);
await put('email-challenge',id,{owner:u.id,email,salt,hash:await hash(salt+code),sent:now(),expires:Date.now()+600000,attempts:0,requests:sameDay?Number(old.requests||0)+1:1},old?.revision);return Response.json({ok:true,message:'Verification code sent. Check your inbox and spam folder.'});
}else if(b.action==='verify'){if(!old||old.expires<Date.now()||old.attempts>=5||old.used)throw new Error('This code has expired or reached its attempt limit. Request a new code.');await put('email-challenge',id,{...old,attempts:old.attempts+1},old.revision);if(await hash(old.salt+String(b.code))!==old.hash)throw new Error('Incorrect code. Try again.');const current=await get(id);await put('email-challenge',id,{...current,used:true},current.revision);await put('profile','profile:'+u.id,{...(profile||{}),owner:u.id,email:old.email,emailVerified:true,verifiedAt:now(),courses:profile?.courses||['UP 406','UP 417']},profile?.revision);return Response.json({ok:true,message:'Email verified. You can receive course reminders.'});}throw new Error('Unsupported email action.');}catch(e:any){return Response.json({error:e.message},{status:400});}}
