'use client';
import {courseworkMaximum} from '../../lib/assessment-scheme';
import {useEffect,useState} from 'react';
import {Plus,Upload,Clock,Download,ChevronDown,FileText,ListChecks,PenLine,FileUp,Timer,Trash2,Eye,ClipboardList,Users,User} from 'lucide-react';
import {Badge,Empty,Modal,UploadZone,Progress,sendForm,date,shortDate,size,remaining} from './ui';

const FORMATS=[
 {id:'Assignment',icon:FileUp,title:'Assignment',body:'Students upload their work (PDF/DOCX, or maps and studio packages).'},
 {id:'Test / quiz file',icon:FileText,title:'Upload a test or quiz file',body:'Share a PDF/DOCX paper. Students download it, answer, and upload their answers.'},
 {id:'Online quiz',icon:ListChecks,title:'Build an online quiz',body:'Multiple choice and short answer, with a time limit and open/close dates.'},
 {id:'Paper test',icon:PenLine,title:'Record a paper test',body:'For tests sat in class. Enter marks only; nothing to upload.'}];
const eat=(v:string)=>v&&!/[Z+]\d*/.test(v.slice(10))?v+'+03:00':v;
const local=(v?:string)=>v?new Date(Date.parse(v)+10800000).toISOString().slice(0,16):'';

// Student-facing status: Not started / Submitted / Late / Marked (Overdue when nothing arrived by the deadline).
export function submissionStatus(ctx:any,a:any){const {get,user,tick}=ctx;if(get('mark').some((m:any)=>m.assessment===a.id&&m.released&&m.student===user.id))return 'Marked';if(a.type==='Online quiz'){const at=get('attempt').find((t:any)=>t.assessment===a.id);if(at?.submitted)return at.late?'Late':'Submitted';}else if(a.type!=='Paper test'){const subs=get('submission').filter((s:any)=>s.assessment===a.id).sort((x:any,y:any)=>y.version-x.version);if(subs.length)return subs[0].late?'Late':'Submitted';}if(a.due&&Date.parse(a.due)<tick)return a.type==='Paper test'?'Not started':'Overdue';return 'Not started';}

export default function Assessments({ctx}:any){const {admin,get,courseCodes}=ctx;const [course,setCourse]=useState('All');const [editor,setEditor]=useState<any>(null);const [quiz,setQuiz]=useState<any>(null);const [review,setReview]=useState<any>(null);
 const list=get('assessment').filter((a:any)=>course==='All'||a.course===course).sort((a:any,b:any)=>(Date.parse(a.due)||9e15)-(Date.parse(b.due)||9e15));
 return <section className="stack reveal">
  <div className="toolbar">{courseCodes.length>1&&<div className="segmented">{['All',...courseCodes].map((c:string)=><button key={c} className={course===c?'selected':''} onClick={()=>setCourse(c)}>{c==='All'?'All courses':c}</button>)}</div>}{admin&&<button className="primary push" onClick={()=>ctx.guard()&&setEditor({})}><Plus size={18}/>Create assessment</button>}</div>
  {list.length?<div className="assessment-list">{list.map((a:any)=>admin?<LecturerCard key={a.id} ctx={ctx} a={a} edit={()=>ctx.guard()&&setEditor(a)} review={()=>setReview(a)}/>:<StudentCard key={a.id} ctx={ctx} a={a} startQuiz={()=>setQuiz(a)}/>)}</div>
   :<Empty icon={ClipboardList} title={admin?'No assessments yet':'No assignments yet'} body={admin?'Create your first one: an assignment, a test paper, an online quiz or a paper test.':'Your lecturer will post assignments here.'} action={admin&&<button className="primary" onClick={()=>ctx.guard()&&setEditor({})}><Plus size={18}/>Create your first assessment</button>}/>}
  {admin&&<Submissions ctx={ctx}/>}
  {editor&&<AssessmentEditor ctx={ctx} record={editor.id?editor:null} close={()=>setEditor(null)}/>}
  {quiz&&<QuizTake ctx={ctx} a={quiz} close={()=>setQuiz(null)}/>}
  {review&&<QuizReview ctx={ctx} a={review} close={()=>setReview(null)}/>}
 </section>;}

function Meta({a}:any){return <div className="meta-row"><span><Clock size={16}/>{a.due?'Due '+shortDate(a.due):'No deadline set'}</span><span>{a.mode==='Group'?<Users size={16}/>:<User size={16}/>}{a.mode}</span><span>{a.max} marks</span>{a.type==='Online quiz'&&<span><Timer size={16}/>{a.timeLimit} min</span>}</div>;}
function FileLinks({ctx,ids}:any){const files=ctx.get('file').filter((f:any)=>(ids||[]).includes(f.id));return files.length?<ul className="file-list">{files.map((f:any)=><li key={f.id}><FileText size={16}/><a href={'/api/files?id='+f.id}>{f.filename}</a><small>{size(f.size)}</small><Download size={16}/></li>)}</ul>:null;}

function StudentCard({ctx,a,startQuiz}:any){const {get,tick,data,refresh,toast,guard}=ctx;const status=submissionStatus(ctx,a);const [openCard,setOpen]=useState(false),[files,setFiles]=useState<File[]>([]),[note,setNote]=useState(''),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
 const subs=get('submission').filter((s:any)=>s.assessment===a.id).sort((x:any,y:any)=>y.version-x.version);const past=a.due&&Date.parse(a.due)<tick;const canSubmit=!['Online quiz','Paper test'].includes(a.type)&&!(past&&subs.length);const group=a.mode==='Group'?get('group')[0]:null;const docsOnly=a.accept!=='documents-images-zip'&&!['Maps / images','Studio package'].includes(a.type);const mark=get('mark').find((m:any)=>m.assessment===a.id&&m.released);const attempt=get('attempt').find((t:any)=>t.assessment===a.id);const notYetOpen=!!a.opens&&Date.parse(a.opens)>tick;
 async function submit(){if(!guard())return;if(!files.length){toast('Choose at least one file.','error');return;}if(a.mode==='Group'&&!group){toast('You need a group before submitting group work.','error');return;}setBusy(true);setDone(false);try{const fd=new FormData();files.forEach(f=>fd.append('files',f));fd.set('assessment',a.id);fd.set('group',group?.id||'');fd.set('note',note);fd.set('semester',data.semester);await sendForm('/api/files',fd,setProgress);setDone(true);await refresh();setFiles([]);setNote('');toast(subs.length?'Resubmitted. Your new version is saved.':'Submitted. Your lecturer can now see your work.');}catch(e:any){toast(e.message,'error');}finally{setBusy(false);}}
 return <article className={'card assessment'+(openCard?' expanded':'')}>
  <button className="assessment-head" aria-expanded={openCard} onClick={()=>setOpen(!openCard)}><span className="grow"><span className="eyebrow">{a.course} · {a.type}</span><h3>{a.title}</h3><Meta a={a}/></span><Badge>{status}</Badge><ChevronDown className="chev" size={20}/></button>
  {openCard&&<div className="assessment-body">
   {a.instructions&&<p className="prewrap">{a.instructions}</p>}
   {a.files?.length>0&&<><h4>Test paper</h4><FileLinks ctx={ctx} ids={a.files}/></>}
   {mark&&<div className="result"><strong>{mark.score} / {a.max}</strong><span>{mark.feedback||'No written feedback.'}</span></div>}
   {a.type==='Paper test'&&!mark&&<p className="quiet">This test is sat in class. Your mark will appear here when it is released.</p>}
   {a.type==='Online quiz'&&!attempt?.submitted&&<div className="quiz-start"><p>{a.questions?.length} questions · {a.timeLimit} minutes once you start{a.opens?` · opens ${shortDate(a.opens)}`:''}. The timer keeps running if you leave the page.</p>{(past||notYetOpen)&&<p role="status">{past?`This quiz closed on ${date(a.due)} EAT. Ask your lecturer to reopen it.`:`This quiz opens on ${date(a.opens)} EAT.`}</p>}<button className="primary" disabled={notYetOpen||!!past} onClick={startQuiz}><Timer size={18}/>{past?'Quiz closed':notYetOpen?'Not open yet':attempt?'Continue quiz':'Start quiz'}</button></div>}
   {a.type==='Online quiz'&&attempt?.submitted&&<p className="quiet">Submitted {date(attempt.submitted)}. {attempt.needsReview?'Short answers will be reviewed by your lecturer.':''}</p>}
   {canSubmit&&<div className="submit-area"><h4>{subs.length?'Resubmit (replaces your latest version)':'Your submission'}</h4><UploadZone files={files} setFiles={setFiles} accept={docsOnly?'.pdf,.doc,.docx':'.pdf,.doc,.docx,.jpg,.jpeg,.png,.webp,.tif,.tiff,.zip'} hint={(docsOnly?'PDF or DOCX':'PDF, DOCX, images or ZIP')+' · max 20 MB each'}/><label>Note to your lecturer (optional)<textarea rows={2} value={note} onChange={e=>setNote(e.target.value)}/></label>{(busy||done)&&<Progress value={progress} done={done}/>}<button className="primary" disabled={busy} onClick={submit}><Upload size={18}/>{busy?'Uploading…':subs.length?'Resubmit':'Submit'}</button>{past&&<p className="footnote">The deadline has passed, so this will be marked late.</p>}</div>}
   {past&&subs.length>0&&a.type!=='Online quiz'&&<p className="quiet">The deadline has passed. Your latest version stands.</p>}
   {subs.length>0&&<><h4>Version history</h4><ul className="versions">{subs.map((s:any)=><li key={s.id}><span className="version">v{s.version}</span><span className="grow">{get('file').filter((f:any)=>(s.files||[]).includes(f.id)).map((f:any)=><a key={f.id} href={'/api/files?id='+f.id}>{f.filename} <small>{size(f.size)}</small></a>)}<small>{date(s.submitted)}{s.author?' · '+s.author:''}</small>{s.feedback&&<small className="feedback">Feedback: {s.feedback}</small>}</span>{s.late&&<Badge>Late</Badge>}</li>)}</ul></>}
  </div>}
 </article>;}

function LecturerCard({ctx,a,edit,review}:any){const {get,action}=ctx;const subs=get('submission').filter((s:any)=>s.assessment===a.id);const marks=get('mark').filter((m:any)=>m.assessment===a.id);const attempts=get('attempt').filter((t:any)=>t.assessment===a.id&&t.submitted);const people=new Set(subs.map((s:any)=>s.group||s.owner)).size;
 return <article className="card assessment lecturer-card"><div className="assessment-head static"><span className="grow"><span className="eyebrow">{a.course} · {a.type}</span><h3>{a.title}</h3><Meta a={a}/></span><Badge>{a.published?'Published':'Draft'}</Badge></div>
  <div className="assessment-stats"><span><b>{a.type==='Online quiz'?attempts.length:a.type==='Paper test'?marks.length:people}</b>{a.type==='Online quiz'?'attempts':a.type==='Paper test'?'marked':'submitted'}</span><span><b>{marks.length}</b>marks recorded</span>{a.weight!==''&&a.weight!==undefined&&<span><b>{a.weight}%</b>of coursework</span>}</div>
  <div className="card-actions"><label className="switch"><input type="checkbox" checked={!!a.marksReleased} onChange={e=>action({action:'releaseMarks',id:a.id,released:e.target.checked},e.target.checked?'Marks released to students':'Marks hidden from students')}/><span className="track"/><span>Release marks</span></label><span className="push"/>{a.type==='Online quiz'&&<button className="secondary" onClick={review}><Eye size={16}/>Answers</button>}<button className="secondary" onClick={()=>ctx.open('mark',undefined,{assessment:a.id,penalty:0,released:!!a.marksReleased})}>Record mark</button><button className="secondary" onClick={edit}>Edit</button></div>
 </article>;}

function Submissions({ctx}:any){const {get,open}=ctx;const subs=get('submission').sort((a:any,b:any)=>b.submitted.localeCompare(a.submitted));if(!subs.length)return null;return <section className="card"><div className="card-head"><h2>Submissions</h2><span className="muted">Every version is kept</span></div><div className="table-wrap"><table><thead><tr><th>Assessment</th><th>From</th><th>Version</th><th>Files</th><th>Feedback</th></tr></thead><tbody>{subs.map((s:any)=><tr key={s.id}><td>{s.title}{s.late&&<> <Badge>Late</Badge></>}</td><td>{s.group?get('group').find((g:any)=>g.id===s.group)?.title:s.author}</td><td>v{s.version}<small>{date(s.submitted)}</small></td><td>{get('file').filter((f:any)=>(s.files||[]).includes(f.id)).map((f:any)=><a className="file-link" key={f.id} href={'/api/files?id='+f.id}>{f.filename}</a>)}</td><td>{s.feedback||<span className="muted">None yet</span>} <button className="text-button" onClick={()=>open('submission',s)}>{s.feedback?'Edit':'Add'}</button></td></tr>)}</tbody></table></div></section>;}

function AssessmentEditor({ctx,record,close}:any){const {courseCodes,action,data,refresh,toast,get}=ctx;const [step,setStep]=useState(record?1:0);const [f,setF]=useState<any>(record?{...record,due:local(record.due),opens:local(record.opens)}:{course:data.selectedCourse||courseCodes[0],mode:'Individual',max:100,weight:'',penalty:0,published:false,accept:'documents',timeLimit:30,questions:[]});const [files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0);
 const set=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));const qs=f.questions||[];const setQ=(i:number,patch:any)=>set('questions',qs.map((q:any,j:number)=>j===i?{...q,...patch}:q));
 async function save(e:any){e.preventDefault();setBusy(true);const d={...f,due:eat(f.due),opens:eat(f.opens)};if(d.type==='Online quiz')d.max=qs.reduce((s:number,q:any)=>s+Number(q.points||1),0)||d.max;const r=await action({action:'save',kind:'assessment',data:d,id:record?.id,revision:record?.revision},'');if(r&&files.length){try{const fd=new FormData();files.forEach(x=>fd.append('files',x));fd.set('brief',r.id);fd.set('semester',data.semester);await sendForm('/api/files',fd,setProgress);await refresh();}catch(err:any){toast(err.message,'error');setBusy(false);return;}}setBusy(false);if(r){toast(record?'Assessment updated':f.published?'Published to students':'Saved as a draft');close();}}
 if(step===0)return <Modal title="Create an assessment" onClose={close}><div className="format-grid">{FORMATS.map(x=>{const Icon=x.icon;return <button key={x.id} className="format-option" onClick={()=>{set('type',x.id);setStep(1);}}><span className="icon-tile"><Icon size={22}/></span><strong>{x.title}</strong><small>{x.body}</small></button>;})}</div></Modal>;
 const type=f.type;
 return <Modal title={(record?'Edit ':'New ')+({'Assignment':'assignment','Test / quiz file':'test or quiz paper','Online quiz':'online quiz','Paper test':'paper test'} as any)[type]||(record?'Edit assessment':'New assessment')} onClose={close} busy={busy} wide><form onSubmit={save}>
  <div className="form-grid">
   <label className="wide">Title<input required value={f.title||''} onChange={e=>set('title',e.target.value)}/></label>
   <label>Course<select value={f.course} onChange={e=>set('course',e.target.value)}>{courseCodes.map((c:string)=><option key={c}>{c}</option>)}</select></label>
   <label>Who does it<select value={f.mode} onChange={e=>set('mode',e.target.value)}><option>Individual</option><option>Group</option></select></label>
   {type!=='Online quiz'&&<label>Maximum mark<input type="number" min={1} required value={f.max} onChange={e=>set('max',e.target.value)}/></label>}
   <label>Coursework contribution (out of {courseworkMaximum(f.course)})<input type="number" min={0} max={courseworkMaximum(f.course)} step="0.01" value={f.weight} onChange={e=>set('weight',e.target.value)} placeholder="Leave blank until confirmed"/></label>
   {type==='Online quiz'&&<label>Opens (East Africa Time)<input type="datetime-local" value={f.opens||''} onChange={e=>set('opens',e.target.value)}/></label>}
   <label>{type==='Online quiz'?'Closes (optional)':type==='Paper test'?'Test date':'Due'} (East Africa Time)<input type="datetime-local" value={f.due||''} onChange={e=>set('due',e.target.value)}/></label>
   {type==='Online quiz'&&<p className="wide footnote">Leave the closing date blank to keep the quiz available. Each student still has the time limit once they start.{f.due&&Date.parse(eat(f.due))<Date.now()?' The selected closing time has passed, so students cannot start this quiz.':''}</p>}
   {type==='Online quiz'&&<label>Time limit (minutes)<input type="number" min={1} max={300} value={f.timeLimit} onChange={e=>set('timeLimit',e.target.value)}/></label>}
   {['Assignment','Test / quiz file'].includes(type)&&<label>Late penalty (% of max)<input type="number" min={0} max={100} value={f.penalty} onChange={e=>set('penalty',e.target.value)}/></label>}
   {['Assignment','Test / quiz file'].includes(type)&&<label>Accepted files<select value={f.accept} onChange={e=>set('accept',e.target.value)}><option value="documents">PDF and DOCX only</option><option value="documents-images-zip">Also images and ZIP (maps, studio packages)</option></select></label>}
   <label className="wide">{type==='Online quiz'?'Instructions':'Brief / questions'}<textarea rows={4} value={f.instructions||''} onChange={e=>set('instructions',e.target.value)}/></label>
  </div>
  {type==='Test / quiz file'&&<div className="below"><h4>Test paper for students to download</h4><FileLinks ctx={ctx} ids={f.files}/><UploadZone files={files} setFiles={setFiles} accept=".pdf,.doc,.docx" hint="PDF or DOCX · 20 MB max"/>{busy&&files.length>0&&<Progress value={progress} done={progress>=1}/>}</div>}
  {type==='Online quiz'&&<div className="quiz-builder below"><div className="card-head"><h4>Questions</h4><span className="muted">{qs.reduce((s:number,q:any)=>s+Number(q.points||1),0)} points</span></div>{qs.map((q:any,i:number)=><div className="question" key={q.id||i}><div className="question-head"><b>Q{i+1}</b><select aria-label="Question type" value={q.type} onChange={e=>setQ(i,{type:e.target.value})}><option value="mc">Multiple choice</option><option value="short">Short answer</option></select><label className="inline">Points<input type="number" min={1} value={q.points} onChange={e=>setQ(i,{points:e.target.value})}/></label><button type="button" className="icon-button" aria-label={'Delete question '+(i+1)} onClick={()=>set('questions',qs.filter((_:any,j:number)=>j!==i))}><Trash2 size={16}/></button></div><textarea rows={2} placeholder="Question" value={q.text} onChange={e=>setQ(i,{text:e.target.value})}/>{q.type==='mc'?<div className="options">{(q.options||[]).map((o:string,j:number)=><label className="option" key={j}><input type="radio" name={'ans'+i} checked={Number(q.answer)===j} onChange={()=>setQ(i,{answer:j})} aria-label="Correct answer"/><input value={o} placeholder={'Option '+(j+1)} onChange={e=>setQ(i,{options:q.options.map((x:string,k:number)=>k===j?e.target.value:x)})}/></label>)}{(q.options||[]).length<8&&<button type="button" className="text-button" onClick={()=>setQ(i,{options:[...(q.options||[]),'']})}><Plus size={14}/>Add option</button>}<small>Select the radio button next to the correct answer.</small></div>:<input placeholder="Model answer (shown only to you when reviewing)" value={q.answer||''} onChange={e=>setQ(i,{answer:e.target.value})}/>}</div>)}<div className="button-row"><button type="button" className="secondary" onClick={()=>set('questions',[...qs,{id:crypto.randomUUID(),type:'mc',text:'',options:['',''],answer:0,points:1}])}><Plus size={16}/>Multiple choice</button><button type="button" className="secondary" onClick={()=>set('questions',[...qs,{id:crypto.randomUUID(),type:'short',text:'',answer:'',points:2}])}><Plus size={16}/>Short answer</button></div></div>}
  <label className="check-label below"><input type="checkbox" checked={!!f.published} onChange={e=>set('published',e.target.checked)}/><span>Publish to students{type==='Paper test'?' (shows the test date and, later, released marks)':''}</span></label>
  <div className="modal-actions">{!record&&<button type="button" className="text-button" onClick={()=>setStep(0)}>Change type</button>}<span className="push"/><button type="button" className="secondary" disabled={busy} onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':f.published?'Save & publish':'Save draft'}</button></div>
 </form></Modal>;}

function QuizTake({ctx,a,close}:any){const {get,action,tick}=ctx;const attempt=get('attempt').find((t:any)=>t.assessment===a.id);const [started,setStarted]=useState<string>(attempt?.started||'');const [answers,setAnswers]=useState<any>({}),[busy,setBusy]=useState(false);
 useEffect(()=>{if(started)return;action({action:'quizStart',id:a.id},'').then((r:any)=>{if(r?.started)setStarted(r.started);else close();});},[]);// eslint-disable-line react-hooks/exhaustive-deps
 const end=started?Math.min(Date.parse(started)+a.timeLimit*60000,a.due?Date.parse(a.due):Infinity):0;const left=end-tick;
 async function submit(e?:any){e?.preventDefault();if(busy)return;setBusy(true);const r=await action({action:'quizSubmit',id:a.id,answers},'Quiz submitted');setBusy(false);if(r)close();}
 useEffect(()=>{if(started&&left<=0&&!busy)submit();},[left<=0]);// eslint-disable-line react-hooks/exhaustive-deps
 return <Modal title={a.title} onClose={close} busy={busy} wide>{!started?<p>Starting your quiz…</p>:<form onSubmit={submit}><div className={'quiz-timer'+(left<120000?' low':'')} role="timer"><Timer size={18}/>{left>0?`${Math.floor(left/60000)}:${String(Math.floor(left%60000/1000)).padStart(2,'0')} left`:'Time is up'}</div>{a.instructions&&<p className="prewrap">{a.instructions}</p>}{a.questions.map((q:any,i:number)=><fieldset className="quiz-q" key={q.id}><legend><b>Q{i+1}.</b> {q.text} <small>({q.points} pt{q.points>1?'s':''})</small></legend>{q.type==='mc'?q.options.map((o:string,j:number)=><label className="option-choice" key={j}><input type="radio" name={q.id} checked={answers[q.id]===j} onChange={()=>setAnswers({...answers,[q.id]:j})}/><span>{o}</span></label>):<textarea rows={3} value={answers[q.id]||''} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}/>}</fieldset>)}<p className="footnote">Leaving this window does not pause the timer. You can submit only once.</p><div className="modal-actions"><button className="primary" disabled={busy}>{busy?'Submitting…':'Submit answers'}</button></div></form>}</Modal>;}

function QuizReview({ctx,a,close}:any){const {get,member,open}=ctx;const attempts=get('attempt').filter((t:any)=>t.assessment===a.id&&t.submitted);return <Modal title={'Answers · '+a.title} onClose={close} wide>{attempts.length?attempts.map((t:any)=>{const m=get('mark').find((m:any)=>m.assessment===a.id&&m.student===t.owner);return <section className="review" key={t.id}><div className="card-head"><h4>{member(t.owner)}</h4><span className="muted">Auto-marked {t.autoPoints}/{t.totalPoints}{t.late?' · late':''}</span><button className="secondary" onClick={()=>{close();open('mark',m,{assessment:a.id,student:t.owner});}}>{m?'Adjust mark':'Record mark'}</button></div>{a.questions.filter((q:any)=>q.type==='short').map((q:any)=><div className="short-answer" key={q.id}><small>{q.text}</small><p>{t.answers?.[q.id]||<em>No answer</em>}</p>{q.answer&&<small className="muted">Model answer: {q.answer}</small>}</div>)}</section>;}):<Empty title="No attempts yet" body="Submitted quiz answers will appear here."/>}</Modal>;}
