'use client';
import {useState} from 'react';
import {Plus,FileText,Link2,ChevronDown,Trash2,FolderOpen,Presentation,Image as ImageIcon,Download} from 'lucide-react';
import {Badge,Empty,Modal,UploadZone,Progress,sendForm,size} from './ui';
import ResourceLibrary from './ResourceLibrary';

const icon=(name:string)=>/\.(pptx?|key)$/i.test(name)?Presentation:/\.(png|jpe?g|webp)$/i.test(name)?ImageIcon:FileText;

export default function CourseMaterials({ctx}:any){const {admin,get,settings,courseCodes,data,week:currentWeek,records,open,archived}=ctx;const [course,setCourse]=useState(data.selectedCourse||courseCodes[0]);const [adding,setAdding]=useState<number|null>(null);const weeks=Math.max(1,Number(settings.weeks)||15);
 const materials=get('material').filter((m:any)=>m.course===course);
 const [expanded,setExpanded]=useState<number[]>(()=>{const w=currentWeek&&currentWeek>=1?currentWeek:Math.min(...materials.map((m:any)=>m.week),99);return w<99?[w]:[1];});
 const toggle=(w:number)=>setExpanded(x=>x.includes(w)?x.filter(y=>y!==w):[...x,w]);
 const any=get('material').length>0;
 return <div className="stack reveal">
  <div className="toolbar">{courseCodes.length>1&&<div className="segmented">{courseCodes.map((c:string)=><button key={c} className={course===c?'selected':''} onClick={()=>setCourse(c)}>{c}</button>)}</div>}<span className="muted push">{materials.length} item{materials.length===1?'':'s'}</span></div>
  {!admin&&!any?<Empty icon={FolderOpen} title="No course materials yet" body="Your lecturers will add notes, slides and readings for each week here."/>:
  <div className="weeks">{Array.from({length:weeks},(_,i)=>i+1).map(w=>{const items=materials.filter((m:any)=>Number(m.week)===w);if(!admin&&!items.length)return null;const isOpen=expanded.includes(w);return <section className={'week'+(isOpen?' open':'')+(w===currentWeek?' current':'')} key={w}>
   <button className="week-head" aria-expanded={isOpen} onClick={()=>toggle(w)}><span className="week-num">Week {w}</span>{w===currentWeek&&<Badge tone="lime">This week</Badge>}<span className="muted push">{items.length?`${items.length} item${items.length===1?'':'s'}`:'Nothing yet'}</span><ChevronDown className="chev" size={20}/></button>
   {isOpen&&<div className="week-body">{items.map((m:any)=><article className="material" key={m.id}><div className="grow"><strong>{m.title}</strong>{m.published===false&&<> <Badge>Draft</Badge></>}{m.notes&&<p className="prewrap">{m.notes}</p>}<ul className="file-list">{get('file').filter((f:any)=>(m.files||[]).includes(f.id)).map((f:any)=>{const I=icon(f.filename);return <li key={f.id}><I size={16}/><a href={'/api/files?id='+f.id}>{f.filename}</a><small>{size(f.size)}</small><Download size={16}/></li>;})}{m.url&&<li><Link2 size={16}/><a href={m.url} target="_blank" rel="noreferrer">{m.url.replace(/^https?:\/\//,'').slice(0,60)}</a></li>}</ul></div>{admin&&!archived&&<div className="row-actions"><button className="text-button" onClick={()=>open('material',m)}>Edit</button><button className="icon-button" aria-label={'Remove '+m.title} onClick={()=>confirm(`Remove “${m.title}”? Students will no longer see it.`)&&ctx.action({action:'deleteMaterial',id:m.id},'Material removed')}><Trash2 size={16}/></button></div>}</article>)}{admin&&<button className="secondary add-material" onClick={()=>ctx.guard()&&setAdding(w)}><Plus size={16}/>Add to week {w}</button>}</div>}
  </section>;})}</div>}
  {(admin||get('resource').length>0)&&<section className="stack"><div className="card-head"><h2>Datasets & shapefiles</h2></div><ResourceLibrary records={records} admin={admin&&!archived} open={open}/></section>}
  {adding!==null&&<AddMaterial ctx={ctx} course={course} week={adding} close={()=>setAdding(null)}/>}
 </div>;}

function AddMaterial({ctx,course,week,close}:any){const {data,refresh,toast,action}=ctx;const [f,setF]=useState({title:'',notes:'',url:'',published:true}),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0);
 async function save(e:any){e.preventDefault();if(!files.length&&!f.url){toast('Attach a file or add a link.','error');return;}setBusy(true);try{if(files.length){const fd=new FormData();fd.set('material','true');fd.set('course',course);fd.set('week',String(week));fd.set('title',f.title);fd.set('notes',f.notes);fd.set('published',f.published?'on':'off');fd.set('semester',data.semester);files.forEach(x=>fd.append('files',x));await sendForm('/api/files',fd,setProgress);if(f.url){await refresh();const created=ctx.get('material').find((m:any)=>m.title===f.title&&Number(m.week)===week);if(created)await action({action:'save',kind:'material',id:created.id,revision:created.revision,data:{...created,url:f.url}},'');}await refresh();toast('Added to week '+week);close();}else{const r=await action({action:'save',kind:'material',data:{...f,course,week,files:[]}},'Added to week '+week);if(r)close();}}catch(err:any){toast(err.message,'error');}finally{setBusy(false);}}
 return <Modal title={`Add to week ${week} · ${course}`} onClose={close} busy={busy}><form onSubmit={save}><div className="form-grid"><label className="wide">Title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="e.g. Lecture 3 slides"/></label><div className="wide"><UploadZone files={files} setFiles={setFiles} accept=".pdf,.doc,.docx,.ppt,.pptx,.xlsx,.csv,.jpg,.jpeg,.png,.webp,.zip" hint="PDF, DOCX, PPTX or images · 20 MB each"/></div><label className="wide">Or a link<input type="url" value={f.url} onChange={e=>setF({...f,url:e.target.value})} placeholder="https://"/></label><label className="wide">Notes for students (optional)<textarea rows={3} value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><label className="check-label wide"><input type="checkbox" checked={f.published} onChange={e=>setF({...f,published:e.target.checked})}/><span>Visible to students now</span></label></div>{busy&&files.length>0&&<Progress value={progress} done={progress>=1}/>}<div className="modal-actions"><button type="button" className="secondary" onClick={close} disabled={busy}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Add material'}</button></div></form></Modal>;}
