'use client';
import {useState} from 'react';
import {Users,Upload,Plus,Activity,FileText,Trash2} from 'lucide-react';
import {Badge,Empty,date,size} from './ui';
import {Avatar} from './ProfileMenu';

export default function Groups({ctx}:any){const {admin,get,member,open,action}=ctx;const groups=get('group');const [selected,setSelected]=useState('');
 if(!groups.length)return <Empty icon={Users} title={admin?'No groups yet':'You’re not in a group yet'} body={admin?'Form groups automatically from enrolled students, or create one yourself.':'Your lecturer will place you in a studio group. It will show up here.'} action={admin&&<div className="button-row center"><button className="secondary" onClick={()=>open('autoGroups',undefined,{size:5})}>Form groups automatically</button><button className="primary" onClick={()=>open('group',undefined,{members:[]})}><Plus size={18}/>Create group</button></div>}/>;
 const g=groups.find((x:any)=>x.id===selected)||groups[0];const items=(kind:string)=>get(kind).filter((r:any)=>r.group===g.id);const tasks=items('task');
 return <div className="stack reveal">
  {(admin||groups.length>1)&&<div className="toolbar"><div className="segmented wrap">{groups.map((x:any)=><button key={x.id} className={g.id===x.id?'selected':''} onClick={()=>setSelected(x.id)}>{x.title} <small>{x.members?.length||0}</small></button>)}</div>{admin&&<div className="button-row push"><button className="secondary" onClick={()=>open('autoGroups',undefined,{size:5})}>Form automatically</button><button className="primary" onClick={()=>open('group',undefined,{members:[]})}><Plus size={18}/>New group</button></div>}</div>}
  <section className="card tint-sky"><div className="card-head"><div><span className="eyebrow">{g.course}</span><h2>{g.title}</h2>{g.description&&<p>{g.description}</p>}</div>{admin&&<div className="button-row"><button className="secondary" onClick={()=>open('group',g)}>Edit</button><button className="secondary danger" onClick={()=>ctx.guard()&&confirm(`Delete “${g.title}”? Its tasks and activity are removed. Work already submitted stays.`)&&action({action:'deleteGroup',id:g.id},'Group deleted').then((r:any)=>r&&setSelected(''))}><Trash2 size={16}/>Delete</button></div>}</div><div className="members">{(g.members||[]).map((id:string)=><span className="member" key={id}><Avatar user={{id,name:member(id)}} size="small"/>{member(id)}</span>)}</div></section>
  <div className="card-row two">
   <section className="card"><div className="card-head"><h2>Tasks</h2><button className="secondary" onClick={()=>open('task',undefined,{group:g.id,status:'To do'})}><Plus size={16}/>Add task</button></div>{tasks.length?tasks.map((t:any)=><div className="list-row static" key={t.id}><span className="grow"><strong>{t.title}</strong><small>{t.assignee||'Unassigned'}{t.due?' · due '+t.due:''}</small></span><Badge>{t.status}</Badge>{t.status!=='Done'&&<button className="text-button" onClick={()=>action({action:'task',id:t.id,group:g.id,data:{...t,status:t.status==='To do'?'In progress':'Done'}},'Task updated')}>{t.status==='To do'?'Start':'Mark done'}</button>}<button className="text-button" onClick={()=>open('task',t)}>Edit</button></div>):<p className="quiet">Split the work: add tasks and who is responsible.</p>}</section>
   <section className="card"><div className="card-head"><h2>Shared files</h2><button className="secondary" onClick={()=>open('upload',undefined,{group:g.id})}><Upload size={16}/>Upload</button></div>{items('file').length?<ul className="file-list">{items('file').map((f:any)=><li key={f.id}><FileText size={16}/><a href={'/api/files?id='+f.id}>{f.filename}</a><small>{size(f.size)} · {f.author}</small></li>)}</ul>:<p className="quiet">Drafts, maps and studio files you share with your group.</p>}</section>
  </div>
  {items('activity').length>0&&<section className="card"><div className="card-head"><h2>Recent activity</h2></div>{items('activity').sort((a:any,b:any)=>b.created.localeCompare(a.created)).slice(0,8).map((a:any)=><div className="list-row static" key={a.id}><Activity size={16}/><span className="grow">{a.title}</span><small>{date(a.created)}</small></div>)}</section>}
 </div>;}
