'use client';
import {useState} from 'react';
import {Mail,Plus,FileText,MessageSquareReply} from 'lucide-react';
import {Badge,Empty,Modal,UploadZone,Progress,sendForm,date,size} from './ui';

const TYPES=['Absence/excuse letter','Apology letter','Extension request','Other'];
const STATUSES=['Received','Under review','Approved','Declined'];

function Attachments({ctx,ids}:any){return <ul className="file-list">{ctx.get('file').filter((f:any)=>(ids||[]).includes(f.id)).map((f:any)=><li key={f.id}><FileText size={16}/><a href={'/api/files?id='+f.id}>{f.filename}</a><small>{size(f.size)}</small></li>)}</ul>;}

export default function Letters({ctx}:any){const {admin,get,courseCodes}=ctx;const [composing,setComposing]=useState(false),[selected,setSelected]=useState<any>(null),[filters,setFilters]=useState({type:'',status:'',course:''});
 const letters=get('letter').filter((l:any)=>(!filters.type||l.type===filters.type)&&(!filters.status||l.status===filters.status)&&(!filters.course||l.course===filters.course)).sort((a:any,b:any)=>(b.submitted||'').localeCompare(a.submitted||''));
 return <div className="stack reveal">
  {admin?<div className="toolbar filters">{([['type','All types',TYPES],['status','All statuses',STATUSES],['course','All courses',courseCodes]] as const).map(([k,label,opts])=><select key={k} aria-label={'Filter by '+k} value={(filters as any)[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}><option value="">{label}</option>{(opts as readonly string[]).map(o=><option key={o}>{o}</option>)}</select>)}<span className="muted push">{get('letter').filter((l:any)=>l.status==='Received').length} new</span></div>
  :<div className="toolbar"><p className="muted grow">Send absence letters, apologies and extension requests to your lecturers. Only you and your lecturers can see them.</p><button className="primary" onClick={()=>ctx.guard()&&setComposing(true)}><Plus size={18}/>New letter</button></div>}
  {letters.length?<div className="card list-card">{letters.map((l:any)=><button className="list-row" key={l.id} onClick={()=>setSelected(l)}><span className="icon-tile"><Mail size={18}/></span><span className="grow"><strong>{l.subject}</strong><small>{admin?l.author+' · ':''}{l.type}{l.course?' · '+l.course:''} · {date(l.submitted)}</small></span><Badge>{l.status}</Badge></button>)}</div>
  :<Empty icon={Mail} title={admin?'No letters yet':'No letters sent yet'} body={admin?'Student letters and requests will arrive here.':'Need to explain an absence or ask for an extension? Send a letter here.'} action={!admin&&<button className="primary" onClick={()=>ctx.guard()&&setComposing(true)}><Plus size={18}/>Write a letter</button>}/>}
  {composing&&<Compose ctx={ctx} close={()=>setComposing(false)}/>}
  {selected&&<LetterView ctx={ctx} letter={get('letter').find((l:any)=>l.id===selected.id)||selected} close={()=>setSelected(null)}/>}
 </div>;}

function Compose({ctx,close}:any){const {courseCodes,data,refresh,toast}=ctx;const [f,setF]=useState({type:TYPES[0],course:'',subject:'',message:''}),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0);
 async function send(e:any){e.preventDefault();if(!files.length){toast('Attach your letter as a PDF, DOCX or photo.','error');return;}setBusy(true);try{const fd=new FormData();Object.entries(f).forEach(([k,v])=>fd.set(k,v));fd.set('letter','true');fd.set('semester',data.semester);files.forEach(x=>fd.append('files',x));await sendForm('/api/files',fd,setProgress);await refresh();toast('Letter sent. You will be notified when your lecturer replies.');close();}catch(err:any){toast(err.message,'error');}finally{setBusy(false);}}
 return <Modal title="New letter" onClose={close} busy={busy}><form onSubmit={send}><div className="form-grid"><label>Type<select value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Course<select value={f.course} onChange={e=>setF({...f,course:e.target.value})}><option value="">Not course-specific</option>{courseCodes.map((c:string)=><option key={c}>{c}</option>)}</select></label><label className="wide">Subject<input required maxLength={120} value={f.subject} onChange={e=>setF({...f,subject:e.target.value})} placeholder="e.g. Absence on 14 October — medical"/></label><label className="wide">Message<textarea rows={4} maxLength={2000} value={f.message} onChange={e=>setF({...f,message:e.target.value})}/></label><div className="wide"><UploadZone files={files} setFiles={setFiles} accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.webp" hint="PDF, DOCX or a photo of the letter · up to 3 files, 20 MB each"/></div></div>{busy&&<Progress value={progress} done={progress>=1}/>}<div className="modal-actions"><button type="button" className="secondary" onClick={close} disabled={busy}>Cancel</button><button className="primary" disabled={busy}>{busy?'Sending…':'Send letter'}</button></div></form></Modal>;}

function LetterView({ctx,letter:l,close}:any){const {admin,get,action}=ctx;const [status,setStatus]=useState(l.status==='Received'?'Under review':l.status),[reply,setReply]=useState(l.reply||''),[excuse,setExcuse]=useState(''),[busy,setBusy]=useState(false);
 const absences=get('attendance').filter((a:any)=>a.student===l.owner&&['Absent','Late'].includes(a.status));const session=(id:string)=>get('session').find((s:any)=>s.id===id);
 async function save(e:any){e.preventDefault();setBusy(true);const r=await action({action:'letterReply',id:l.id,status,reply,excuse:status==='Approved'?excuse:''},'Reply sent to the student');setBusy(false);if(r)close();}
 return <Modal title={l.subject} onClose={close} busy={busy} wide>
  <div className="letter-meta"><Badge>{l.status}</Badge><span>{l.type}</span>{l.course&&<span>{l.course}</span>}<span>{admin?l.author+' · ':''}{date(l.submitted)}</span></div>
  {l.message&&<p className="prewrap letter-body">{l.message}</p>}
  <Attachments ctx={ctx} ids={l.files}/>
  {!admin&&(l.reply||l.status!=='Received')&&<div className="reply"><MessageSquareReply size={18}/><div><strong>{l.repliedBy||'Lecturer'} · {l.status}</strong><p className="prewrap">{l.reply||'No message added.'}</p>{l.excused&&<small>Linked absence marked as excused.</small>}</div></div>}
  {admin&&<form onSubmit={save} className="below"><div className="form-grid"><label>Decision<select value={status} onChange={e=>setStatus(e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></label>{status==='Approved'&&absences.length>0&&<label>Mark an absence as excused<select value={excuse} onChange={e=>setExcuse(e.target.value)}><option value="">Don’t change attendance</option>{absences.map((a:any)=><option key={a.id} value={a.id}>{session(a.session)?.title||'Class'} · {date(session(a.session)?.started)} · {a.status}</option>)}</select></label>}<label className="wide">Reply to the student<textarea rows={4} value={reply} onChange={e=>setReply(e.target.value)} placeholder={status==='Declined'?'Explain the decision':'Optional'}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={close} disabled={busy}>Close</button><button className="primary" disabled={busy}>{busy?'Sending…':'Send reply'}</button></div></form>}
 </Modal>;}
