'use client';
import {schemeFor,courseworkMaximum} from '../../lib/assessment-scheme';
import {GraduationCap,ShieldCheck} from 'lucide-react';
import {Badge,Empty,CountUp} from './ui';

const net=(m:any,a:any)=>Math.max(0,Number(m.score)-(m.waived?0:Number(m.penalty||0)/100*Number(a?.max||0)));
// Coursework total only counts once weights for every published assessment add up to the course’s coursework allocation and the scheme is approved.
export function courseTotal(get:any,settings:any,course:string,student:string){const a=get('assessment').filter((x:any)=>x.course===course&&x.published);const marks=get('mark').filter((m:any)=>m.student===student&&m.released);const maximum=courseworkMaximum(course);const configured=!!schemeFor(settings,course,a).approved&&a.length>0&&a.every((x:any)=>x.weight!==''&&x.weight!==undefined)&&Math.abs(a.reduce((s:number,x:any)=>s+Number(x.weight),0)-maximum)<.01;const total=a.reduce((s:number,x:any)=>{const m=marks.find((m:any)=>m.assessment===x.id);return s+(m?net(m,x)/Number(x.max)*Number(x.weight):0);},0);return {configured,total,maximum,marked:marks.filter((m:any)=>a.some((x:any)=>x.id===m.assessment)).length,count:a.length};}

export default function Marks({ctx}:any){const {admin,get,settings,user,courseCodes,member,students,open}=ctx;const assessment=(id:string)=>get('assessment').find((a:any)=>a.id===id);const marks=get('mark').sort((a:any,b:any)=>(b.created||'').localeCompare(a.created||''));
 if(!admin)return <div className="stack reveal">
  <div className="card-row two">{courseCodes.map((c:string,i:number)=>{const t=courseTotal(get,settings,c,user.id);return <section className={'card stat-card '+(i%2?'tint-lilac':'tint-sky')} key={c}><span className="card-label">{c} · coursework</span><strong className="big">{t.configured?<><CountUp value={t.total} decimals={1}/><small> / {t.maximum}</small></>:'—'}</strong><p>{t.configured?`${t.marked} of ${t.count} assessments marked. Unmarked work counts as zero for now.`:'Your total appears once the lecturer confirms the assessment weights.'}</p></section>;})}</div>
  <section className="card"><div className="card-head"><h2>Marks & feedback</h2></div>{marks.length?<div className="feedback-list">{marks.map((m:any)=>{const a=assessment(m.assessment);return <article className="feedback-item" key={m.id}><div className="score"><b>{net(m,a).toFixed(1)}</b><small>/ {a?.max}</small></div><div className="grow"><span className="eyebrow">{a?.course} · {a?.type}</span><h3>{a?.title||'Assessment'}</h3>{Number(m.penalty)>0&&<small>{m.waived?'Late penalty waived':`Late penalty ${m.penalty}%`}{m.reason?' · '+m.reason:''}</small>}<p className="prewrap">{m.feedback||'No written feedback.'}</p></div></article>;})}</div>:<Empty icon={GraduationCap} title="No marks released yet" body="Your marks and private feedback will appear here when your lecturer releases them."/>}</section>
  <p className="footnote">Working teaching record, not official ARU results.</p>
 </div>;
 const activeScheme=schemeFor(settings,ctx.data.selectedCourse,get('assessment').filter((a:any)=>a.course===ctx.data.selectedCourse&&a.published));
 const studentList=students.filter((s:any)=>s.role==='student');
 return <div className="stack">
  <div className="notice"><ShieldCheck size={20}/><div><strong>{activeScheme.approved?'Approved scheme configured':'Assessment scheme awaiting confirmation'}</strong><p>{activeScheme.policy||(activeScheme.approved?'Coursework weights have been confirmed for this course.':'Enter and confirm the published assessment weights in Settings.')}</p><button className="text-button" onClick={()=>ctx.navigate('settings')}>Configure assessment scheme in Settings</button></div></div>
  <section className="card"><div className="card-head"><h2>Marks</h2><button className="secondary" onClick={()=>open('mark',undefined,{penalty:0,waived:false,released:false})}>Record mark</button></div>{marks.length?<div className="table-wrap"><table><thead><tr><th>Student</th><th>Assessment</th><th>Raw</th><th>Penalty</th><th>Net</th><th>Status</th><th/></tr></thead><tbody>{marks.map((m:any)=>{const a=assessment(m.assessment);return <tr key={m.id}><td>{member(m.student)}</td><td>{a?.title}<small>{a?.course}</small></td><td>{m.score} / {a?.max}</td><td>{m.waived?'Waived':(m.penalty||0)+'%'}</td><td><strong>{net(m,a).toFixed(1)}</strong></td><td><Badge>{m.released?'Released':'Draft'}</Badge></td><td><button className="text-button" onClick={()=>open('mark',m)}>Edit</button></td></tr>;})}</tbody></table></div>:<Empty icon={GraduationCap} title="No marks recorded" body="Record marks from an assessment card, or here. Students only see their own released marks."/>}</section>
  {studentList.length>0&&<section className="card"><div className="card-head"><h2>Running coursework totals</h2></div><div className="table-wrap"><table><thead><tr><th>Student</th>{courseCodes.map((c:string)=><th key={c}>{c}</th>)}</tr></thead><tbody>{studentList.map((s:any)=><tr key={s.id}><td>{s.name}</td>{courseCodes.map((c:string)=>{const t=courseTotal(get,settings,c,s.id);return <td key={c}>{t.configured?t.total.toFixed(1)+' / '+t.maximum:<span className="muted">Weights not confirmed</span>}<small>{t.marked}/{t.count} released</small></td>;})}</tr>)}</tbody></table></div></section>}
  <section className="card"><div className="card-head"><h2>Coursework weights</h2></div>{courseCodes.map((c:string)=>{const a=get('assessment').filter((a:any)=>a.course===c&&a.published);const total=a.reduce((s:number,a:any)=>s+Number(a.weight||0),0);return <div className="list-row static" key={c}><strong className="grow">{c}<small>{total}% allocated across {a.length} published assessment{a.length===1?'':'s'}</small></strong><Badge tone={Math.abs(total-courseworkMaximum(c))<0.01?'green':'amber'}>{Math.abs(total-courseworkMaximum(c))<0.01?'Complete':`Must total ${courseworkMaximum(c)}%`}</Badge></div>;})}</section>
 </div>;}
