'use client';
import {useEffect,useRef,useState} from 'react';
import {UserRound,Bell,LogOut,ChevronDown,Settings} from 'lucide-react';
export function Avatar({user,photo,size=''}:any){return photo?<img className={'avatar '+size} src={`/api/files?avatar=${user.id}&v=${encodeURIComponent(photo)}`} alt=""/>:<span className={'avatar '+size} aria-hidden="true">{(user.name||'?').slice(0,1).toUpperCase()}</span>;}
export default function ProfileMenu({user,courses,navigate,photo}:any){const [open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);const role=user.role==='admin'?'Lecturer / administrator':`Student · ${courses.join(' & ')}`;
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);trigger.current?.focus();}if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)&&root.current?.contains(document.activeElement)){const items=Array.from(root.current.querySelectorAll<HTMLElement>('[role="menuitem"]'));if(!items.length)return;e.preventDefault();const i=items.indexOf(document.activeElement as HTMLElement);items[e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus();}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',key);};},[open]);
 function go(page:string,hash=''){setOpen(false);navigate(page);if(hash)setTimeout(()=>document.getElementById(hash)?.scrollIntoView({behavior:'smooth',block:'start'}),60);}
 return <div ref={root} className="profile-menu"><button ref={trigger} className="profile-trigger" aria-haspopup="menu" aria-expanded={open} aria-label={`Account menu for ${user.name}, ${role}`} onClick={()=>setOpen(!open)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);requestAnimationFrame(()=>root.current?.querySelector<HTMLElement>('[role="menuitem"]')?.focus());}}}><Avatar user={user} photo={photo}/><span className="profile-identity"><strong>{user.name}</strong><small>{role}</small></span><ChevronDown size={16} className="chev"/></button>{open&&<div className="profile-dropdown" role="menu" aria-label="Account"><div className="profile-head"><Avatar user={user} photo={photo}/><div><strong>{user.name}</strong><small>{role}</small></div></div><button role="menuitem" onClick={()=>go('profile')}><UserRound size={18}/>My profile</button><button role="menuitem" onClick={()=>go('profile','notifications')}><Bell size={18}/>Notification settings</button>{user.role==='admin'&&<button role="menuitem" onClick={()=>go('settings')}><Settings size={18}/>Settings</button>}<div className="profile-divider"/><a className="signout-link" role="menuitem" href="/" onClick={async e=>{e.preventDefault();const r=await fetch('/api/auth/logout',{method:'POST'});if(r.ok)window.location.assign('/');}}><LogOut size={18}/>Sign out</a></div>}</div>;
}
