'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,Pencil,ShieldCheck,LogOut,Send,BadgeCheck} from 'lucide-react';
import {Badge,Modal,sendForm} from './ui';
import {Avatar} from './ProfileMenu';

const PREFS:[string,string,string][]=[['classes','Class reminders','An email one hour before each class'],['deadlines','Deadlines','A reminder within 24 hours of a due date'],['marks','Marks released','When a mark and feedback are ready'],['roomChanges','Room changes','When a class moves or is rescheduled'],['announcements','Announcements','Important announcements from lecturers']];

export default function ProfilePage({ctx}:any){const {user,get,action,admin,courseCodes,readOnly}=ctx;const profile=get('profile').find((p:any)=>p.owner===user.id)||{};const [cropping,setCropping]=useState<string|null>(null);const fileInput=useRef<HTMLInputElement>(null);
 const save=(patch:any,message:string)=>action({action:'profile',data:{name:user.name,programme:profile.programme,year:profile.year,phone:profile.phone,registration:profile.registration,notifications:profile.notifications,...patch}},message);
 return <div className="profile stack reveal">
  <section className="card profile-hero"><div className="photo-wrap"><Avatar user={user} photo={profile.photo} size="xl"/><button className="photo-button" aria-label="Change profile photo" onClick={()=>ctx.guard()&&fileInput.current?.click()}><Camera size={18}/></button><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{const f=e.target.files?.[0];if(f)setCropping(URL.createObjectURL(f));e.target.value='';}}/></div><div><h2>{user.name}</h2><p>{admin?'Lecturer / administrator':`Student · ${courseCodes.join(' & ')}`}</p></div></section>
  <Details ctx={ctx} profile={profile} save={save}/>
  <EmailSection ctx={ctx} profile={profile}/>
  <section className="card" id="notifications"><div className="card-head"><div><h2>Notifications</h2><p className="muted">Everything also appears in the portal. These control email reminders.</p></div></div>{PREFS.map(([key,label,hint])=><label className="toggle-row" key={key}><span className="grow"><strong>{label}</strong><small>{hint}</small></span><span className="switch"><input type="checkbox" disabled={readOnly} checked={profile.notifications?.[key]!==false} onChange={e=>save({notifications:{...(profile.notifications||{}),[key]:e.target.checked}},`${label} ${e.target.checked?'on':'off'}`)}/><span className="track"/></span></label>)}</section>
  <section className="card"><div className="card-head"><h2>Sign-in & security</h2></div><div className="list-row static"><ShieldCheck size={20}/><span className="grow"><strong>{user.email}</strong><small>Sign in with your Gmail and password. Students can reset their password from the login page by verifying their Gmail.</small></span></div><a className="secondary" href="/" onClick={async e=>{e.preventDefault();const r=await fetch('/api/auth/logout',{method:'POST'});if(r.ok)window.location.assign('/');}}><LogOut size={18}/>Sign out</a></section>
  {cropping&&<Cropper src={cropping} ctx={ctx} close={()=>{URL.revokeObjectURL(cropping);setCropping(null);}}/>}
 </div>;}

function Details({ctx,profile,save}:any){const {user,admin}=ctx;const initial={name:user.name,registration:profile.registration||'',programme:profile.programme||'',year:profile.year||'',phone:profile.phone||''};const [editing,setEditing]=useState(false),[f,setF]=useState(initial),[busy,setBusy]=useState(false);
 const rows:[keyof typeof initial,string,string][]=[['name','Full name','text'],...(admin?[]:[['registration','Registration number','text'],['programme','Programme','text'],['year','Year of study','text']] as any[]),['phone','Phone number','tel']];
 async function submit(e:any){e.preventDefault();setBusy(true);const r=await save(f,'Profile saved');setBusy(false);if(r)setEditing(false);}
 return <section className="card"><form onSubmit={submit}><div className="card-head"><h2>Personal details</h2>{!editing&&<button type="button" className="secondary" onClick={()=>{if(!ctx.guard())return;setF(initial);setEditing(true);}}><Pencil size={16}/>Edit</button>}</div>
  <dl className={'details'+(editing?' editing':'')}>{rows.map(([k,label,type])=>{const locked=k==='registration'&&!!profile.registration;return <div key={k}><dt><label htmlFor={'p-'+k}>{label}</label></dt><dd>{editing&&!locked?<input id={'p-'+k} type={type} value={(f as any)[k]} placeholder={k==='programme'?'e.g. BSc Urban & Regional Planning':k==='year'?'e.g. Year 4':k==='phone'?'+255 7XX XXX XXX':''} onChange={e=>setF({...f,[k]:e.target.value})} required={k==='name'}/>:<>{(editing?(f as any)[k]:initial[k])||<span className="muted">Not added</span>}{locked&&editing&&<small className="muted"> · set by your lecturer</small>}</>}</dd></div>;})}</dl>
  {editing&&<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save'}</button></div>}
 </form></section>;}

function EmailSection({ctx,profile}:any){const {user,toast,refresh,guard}=ctx;const [status,setStatus]=useState<any>(null),[step,setStep]=useState<'idle'|'email'|'code'>('idle'),[email,setEmail]=useState(profile.email||user.email||''),[code,setCode]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(ctx.readOnly)return;fetch('/api/email').then(r=>r.json()).then(setStatus).catch(()=>{});},[ctx.readOnly]);
 async function call(act:string){setBusy(true);try{const r=await fetch('/api/email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:act,email,code})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);toast(d.message||'Done');if(act==='request')setStep('code');else{setStep('idle');setCode('');await refresh();}}catch(e:any){toast(e.message,'error');}finally{setBusy(false);}}
 const verified=profile.emailVerified;
 return <section className="card"><div className="card-head"><div><h2>Email for reminders</h2><p className="muted">Where deadline and class reminders are sent.</p></div></div>
  <div className="list-row static"><span className="grow"><strong>{profile.email||user.email}</strong></span>{verified?<Badge tone="green"><BadgeCheck size={14}/>Verified</Badge>:step==='idle'&&<button className="secondary" onClick={()=>{if(!guard())return;if(status&&!status.configured){toast('Email verification isn’t switched on yet. You’ll still see every reminder in the portal.','error');return;}setStep('email');}}>Verify email</button>}</div>
  {verified&&step==='idle'&&<button className="text-button" onClick={()=>guard()&&setStep('email')}>Use a different email</button>}
  {step==='email'&&<div className="inline-form"><label className="grow">Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="secondary" onClick={()=>setStep('idle')} disabled={busy}>Cancel</button><button className="primary" disabled={busy||!email} onClick={()=>call('request')}><Send size={16}/>Send code</button></div>}
  {step==='code'&&<div className="inline-form"><label className="grow">Six-digit code from your inbox<input inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button className="secondary" onClick={()=>setStep('email')} disabled={busy}>Back</button><button className="primary" disabled={busy||code.length!==6} onClick={()=>call('verify')}>Verify</button></div>}
 </section>;}

// Square crop: drag to position, slider to zoom. Output is a 320px JPEG.
function Cropper({src,ctx,close}:any){const {data,refresh,toast}=ctx;const img=useRef<HTMLImageElement|null>(null),canvas=useRef<HTMLCanvasElement>(null);const [zoom,setZoom]=useState(1),[off,setOff]=useState({x:0,y:0}),[busy,setBusy]=useState(false),[ready,setReady]=useState(false);const drag=useRef<any>(null);const S=280;
 useEffect(()=>{const i=new Image();i.onload=()=>{img.current=i;setReady(true);};i.src=src;},[src]);
 useEffect(()=>{const c=canvas.current,i=img.current;if(!c||!i)return;const g=c.getContext('2d')!;const base=S/Math.min(i.width,i.height),w=i.width*base*zoom,h=i.height*base*zoom;const x=Math.min(0,Math.max(S-w,(S-w)/2+off.x)),y=Math.min(0,Math.max(S-h,(S-h)/2+off.y));g.fillStyle='#fff';g.fillRect(0,0,S,S);g.drawImage(i,x,y,w,h);},[zoom,off,ready]);
 async function upload(){const c=canvas.current;if(!c)return;setBusy(true);const out=document.createElement('canvas');out.width=out.height=320;out.getContext('2d')!.drawImage(c,0,0,320,320);const blob:Blob=await new Promise(r=>out.toBlob(b=>r(b!),'image/jpeg',.88));try{const fd=new FormData();fd.set('avatar','true');fd.set('semester',data.semester);fd.append('files',new File([blob],'avatar.jpg',{type:'image/jpeg'}));await sendForm('/api/files',fd);await refresh();toast('Profile photo updated');close();}catch(e:any){toast(e.message,'error');}finally{setBusy(false);}}
 return <Modal title="Crop your photo" onClose={close} busy={busy}><div className="cropper"><canvas ref={canvas} width={S} height={S} onPointerDown={e=>{(e.target as Element).setPointerCapture(e.pointerId);drag.current={x:e.clientX-off.x,y:e.clientY-off.y};}} onPointerMove={e=>{if(drag.current)setOff({x:e.clientX-drag.current.x,y:e.clientY-drag.current.y});}} onPointerUp={()=>drag.current=null} aria-label="Drag to position your photo"/><label>Zoom<input type="range" min={1} max={3} step={.01} value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><small className="muted">Drag the photo to position it.</small></div><div className="modal-actions"><button className="secondary" onClick={close} disabled={busy}>Cancel</button><button className="primary" onClick={upload} disabled={busy||!ready}>{busy?'Saving…':'Save photo'}</button></div></Modal>;}
