'use client';
import {currentLocation} from '../../lib/browser-location';
import {useState} from 'react';
import {Modal,UploadZone,Progress,sendForm} from './ui';

const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const titles:Record<string,string>={student:'Add a student',autoGroups:'Form groups automatically',startSession:'Start attendance checkpoint',checkin:'Check in to class',mark:'Record a mark',attendance:'Correct attendance',submission:'Give feedback',notification:'Post an announcement',group:'Studio group',task:'Group task',timetable:'Class session',settings:'Semester settings',resource:'File details',resourceUpload:'Upload a dataset or file',upload:'Upload to group',material:'Edit material'};

function Field({label,name,type='text',values,value,set,hint,required=false}:any){const id='f-'+name;return <label className={type==='textarea'||type==='checkbox'?'wide'+(type==='checkbox'?' check-label':''):''} htmlFor={id}>{type!=='checkbox'&&<span>{label}</span>}{type==='checkbox'?<><input id={id} type="checkbox" checked={!!value} onChange={e=>set(name,e.target.checked)}/><span>{label}</span></>:type==='textarea'?<textarea id={id} rows={4} value={value??''} onChange={e=>set(name,e.target.value)} required={required}/>:type==='select'?<select id={id} value={value??''} onChange={e=>set(name,e.target.value)} required={required}><option value="">Select…</option>{(values||[]).map((v:any)=>typeof v==='string'?<option key={v} value={v}>{v}</option>:<option key={v.value} value={v.value}>{v.label}</option>)}</select>:<input id={id} type={type} value={value??''} onChange={e=>set(name,e.target.value)} required={required}/>}{hint&&<small>{hint}</small>}</label>;}

export default function RecordForm({ctx,modal,close}:any){
 const {get,students,courseCodes,action,data,refresh,toast}=ctx;
 const [form,setForm]=useState<any>(modal.record?{...modal.record}:{...modal.defaults});const [busy,setBusy]=useState(false),[files,setFiles]=useState<File[]>([]),[progress,setProgress]=useState(0);
 const set=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
 const studentOptions=students.filter((s:any)=>s.role==='student').map((s:any)=>({value:s.id,label:s.name}));
 const fields:any={
  timetable:[['Course','course','select',courseCodes],['Day','day','select',days],['Start time','start','time'],['End time','end','time'],['Room','room'],['Lecturers','lecturers']],
  notification:[['Title','title'],['Type','type','select',['Announcement','Class','Room / class change','Deadline','Marks']],['Message','body','textarea'],['Specific student (leave blank for everyone)','student','select',studentOptions],['Also email it to students now (only students with a verified Gmail)','email','checkbox']],
  group:[['Course','course','select',courseCodes],['Group name','title'],['Description','description','textarea']],
  settings:[['Semester title','title'],['Semester starts','start','date'],['Teaching weeks','weeks','number'],['Expected cohort size','expectedStudents','number']],
  resource:[['Title','title'],['Course','course','select',courseCodes],['Description','description','textarea'],['Source URL','source','url'],['Coordinate system','crs'],['Shared with students','published','checkbox']],
  material:[['Title','title'],['Week','week','number'],['Link (optional)','url','url'],['Notes for students','notes','textarea'],['Visible to students','published','checkbox']],
  student:form.role==='admin'?[['Gmail address','email','email']]:[['Full name (as on the class list)','name'],['Registration number','registration'],['Email','email','email']],
  mark:[['Student','student','select',studentOptions],['Assessment','assessment','select',get('assessment').map((a:any)=>({value:a.id,label:a.title}))],['Raw mark','score','number'],['Late penalty (% of maximum)','penalty','number'],['Penalty waived','waived','checkbox'],['Penalty or waiver reason','reason'],['Private feedback to the student','feedback','textarea'],['Release to the student now','released','checkbox']],
  attendance:[['Status','status','select',['Present','Late','Absent','Excused']],['Reason for the correction','reason','textarea']],
  submission:[['Feedback','feedback','textarea']],
  autoGroups:[['Course','course','select',courseCodes],['Students per group','size','number']],
  startSession:[['Class','timetable','select',get('timetable').map((t:any)=>({value:t.id,label:`${t.course} · ${t.day} ${t.start} · ${t.room}`}))]],
  checkin:[['Six-digit class code','code']],
  task:[['Task','title'],['Who is responsible','assignee'],['Due date','due','date'],['Status','status','select',['To do','In progress','Done']],['Details','body','textarea']]
 };
 async function submit(e:any){e.preventDefault();const k=modal.kind;setBusy(true);let ok:any=null;
  if(k==='resourceUpload'||k==='upload'){try{const fd=new FormData(e.target);files.forEach(f=>fd.append('files',f));fd.set('semester',data.semester);if(k==='resourceUpload'){fd.set('resource','true');fd.set('resourceId',form.resourceId||'');}else fd.set('group',form.group||'');if(!files.length)throw new Error('Choose at least one file.');await sendForm('/api/files',fd,setProgress);await refresh();toast('Files uploaded');ok=true;}catch(err:any){toast(err.message,'error');}}
  else if(k==='student'&&form.role==='admin'){try{const r=await fetch('/api/admin/lecturer-invitations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:form.email})});const result:any=await r.json();if(!r.ok)throw new Error(result.error);toast('Invitation emailed. It expires in 24 hours.');ok=true;}catch(error:any){toast(error.message,'error');}}
  else if(k==='checkin'){try{const location=await currentLocation();ok=await action({action:'checkin',...form,...location},'');}catch(error:any){toast(error.message,'error');}}
  else if(['student','autoGroups','startSession'].includes(k))ok=await action({action:k,...form},k==='checkin'?'':undefined);
  else if(k==='task')ok=await action({action:'task',data:form,id:modal.record?.id,group:form.group});
  else{let d={...form};if(k==='mark'&&!modal.record){const found=get('mark').find((m:any)=>m.student===d.student&&m.assessment===d.assessment);if(found)ok=await action({action:'save',kind:k,data:d,id:found.id,revision:found.revision});else ok=await action({action:'save',kind:k,data:d});}else ok=await action({action:'save',kind:k,data:d,id:modal.record?.id,revision:modal.record?.revision});}
  setBusy(false);if(ok?.emailed){const e=ok.emailed;toast(e.skipped?'Posted. Email sending is not switched on, so it was not emailed.':`Posted and emailed to ${e.sent} student${e.sent===1?'':'s'}${e.failed?` · ${e.failed} failed`:''}${e.notVerified?` · ${e.notVerified} haven’t verified a Gmail yet`:''}.`,e.failed?'error':'success');}if(ok)close();}
 const k=modal.kind;
 return <Modal title={k==='student'&&form.role==='admin'?'Invite a lecturer':(modal.record&&!['attendance','submission'].includes(k)?'Edit ':'')+(titles[k]||'Edit')} onClose={close} busy={busy}><form onSubmit={submit}>
  {k==='resourceUpload'?<div className="form-grid"><label>Title<input name="title" required defaultValue={form.title||''}/></label><label>Category<select name="category" value={form.category||'Shapefile'} onChange={e=>set('category',e.target.value)}>{['Shapefile','Lecture notes','Document','Timetable','Student roster'].map(c=><option key={c}>{c}</option>)}</select></label><label>Course<select name="course" defaultValue={form.course||courseCodes[0]}>{courseCodes.map((c:string)=><option key={c}>{c}</option>)}</select></label><label>Coordinate system<input name="crs" placeholder="e.g. EPSG:21037" defaultValue={form.crs||''}/></label><label className="wide">Description<textarea name="description" defaultValue={form.description||''}/></label><label className="wide">Source URL<input type="url" name="source" defaultValue={form.source||''}/></label>{form.category!=='Student roster'&&<label className="check-label wide"><input type="checkbox" name="published" defaultChecked={form.published!==false}/><span>Share with enrolled students</span></label>}<div className="wide"><UploadZone files={files} setFiles={setFiles} accept={form.category==='Shapefile'?'.zip':undefined} hint={form.category==='Shapefile'?'ZIP with matching .shp, .shx, .dbf and .prj · 20 MB max':'Up to 12 files · 20 MB each'}/></div></div>
  :k==='upload'?<><UploadZone files={files} setFiles={setFiles} hint="Reports, map images or studio files · 20 MB each"/><label className="below">Note for your group<textarea name="note" rows={3}/></label></>
  :<div className="form-grid">{(fields[k]||[]).map(([label,name,type,values]:any)=><Field key={name} label={label} name={name} type={type} values={values} value={form[name]} set={set} required={['title','name','email','code','score','status','day','start','end','registration','password'].includes(name)}/>)}{k==='group'&&<fieldset className="wide"><legend>Members</legend><div className="check-grid">{students.filter((s:any)=>s.role==='student').map((s:any)=><label className="check-label" key={s.id}><input type="checkbox" checked={(form.members||[]).includes(s.id)} onChange={e=>set('members',e.target.checked?[...(form.members||[]),s.id]:(form.members||[]).filter((id:string)=>id!==s.id))}/><span>{s.name}</span></label>)}</div></fieldset>}</div>}
  {k==='checkin'&&<p className="footnote">Location is checked only when you submit. Allow precise location access; you must be within 50 meters of the lecture hall.</p>}
  {k==='startSession'&&<p className="footnote">The code lasts 3 minutes. Start a new checkpoint at the beginning, middle, or end of class. Each checkpoint keeps a separate attendance record.</p>}
  {k==='mark'&&<p className="footnote">The penalty is a percentage of the maximum mark. Group work is marked per student so feedback stays private.</p>}
  {(k==='resourceUpload'||k==='upload')&&busy&&<Progress value={progress} done={progress>=1}/>}
  <div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':k==='checkin'?'Check in':k==='startSession'?'Start check-in':['upload','resourceUpload'].includes(k)?'Upload':'Save'}</button></div>
 </form></Modal>;
}
