'use client';
import {useEffect,useState} from 'react';
import {Mail,Plus} from 'lucide-react';
import {Badge,date} from './ui';
import AssessmentScheme from './AssessmentScheme';
import AcademicSettings from './AcademicSettings';

export default function SettingsPage({ctx}:any){const {settings,get,open,data,refresh,students,toast}=ctx;const [email,setEmail]=useState<any>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/email').then(r=>r.json()).then(setEmail).catch(()=>{});},[]);
 async function run(){setBusy(true);try{const r=await fetch('/api/reminders',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const d:any=await r.json();if(!r.ok)throw new Error(d.error);toast(!d.due?'Nothing is due right now, so no reminders were needed.':!d.verified?'Reminders are due, but no student has verified a Gmail yet.':`${d.accepted} reminder email${d.accepted===1?'':'s'} sent${d.failed?` · ${d.failed} failed (see Sent emails)`:''}.`,d.failed?'error':'success');}catch(e:any){toast(e.message,'error');}finally{setBusy(false);}}
 const [testTo,setTestTo]=useState('');async function test(){setBusy(true);try{const r=await fetch('/api/email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'test',email:testTo})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);toast(d.message);}catch(e:any){toast(e.message,'error');}finally{setBusy(false);}}
 const staff=students.filter((s:any)=>s.role==='admin');const studentCount=students.filter((s:any)=>s.role==='student').length;const verified=students.filter((s:any)=>s.role==='student'&&get('profile').some((p:any)=>p.owner===s.id&&p.emailVerified&&!/@(sites\.test|example\.(com|org|net|test))$/i.test(p.email||''))).length;
 return <div className="stack reveal">
  <section className="card"><div className="card-head"><h2>Semester details</h2><button className="secondary" onClick={()=>open('settings',get('settings')[0])}>Edit</button></div><dl className="details"><div><dt>Semester</dt><dd>{settings.title}</dd></div><div><dt>Starts</dt><dd>{settings.start||<span className="muted">Not set</span>}</dd></div><div><dt>Teaching weeks</dt><dd>{settings.weeks}</dd></div><div><dt>Expected cohort</dt><dd>{settings.expectedStudents}</dd></div></dl></section>
  <AssessmentScheme key={data.selectedCourse+':'+(settings.revision||0)} ctx={ctx}/>
  <AcademicSettings data={data} refresh={refresh}/>
  <section className="card"><div className="card-head"><h2>Lecturers & administrators</h2><button className="secondary" onClick={()=>open('student',undefined,{role:'admin'})}><Plus size={16}/>Add lecturer</button></div>{staff.map((s:any)=><div className="list-row static" key={s.id}><span className="grow"><strong>{s.name}</strong><small>{s.email}</small></span></div>)}</section>
  <section className="card"><div className="card-head"><div><h2>Email</h2><p className="muted">{email?.configured?<>Sending from <b>{email.sender}</b>.</>:'Not switched on. Students still see everything inside the portal.'}</p></div><Badge tone={email?.configured?'green':'grey'}>{email?.configured?'Connected':'Not connected'}</Badge></div>
   {email?.configured&&<><div className="email-facts"><div><strong>{verified} of {studentCount}</strong><span>students have a verified Gmail and can receive email</span></div><div><strong>Announcements</strong><span>are emailed the moment you post them with “email it to students” ticked</span></div><div><strong>Reminders</strong><span>go out for classes starting within 1 hour and deadlines within 24 hours</span></div></div>
    <div className="list-row static"><span className="grow"><strong>Send reminders now</strong><small>{email.lastRun?'Last sent '+date(email.lastRun)+'. ':''}Only students with a verified Gmail are emailed.</small></span><button className="secondary" disabled={busy} onClick={run}>{busy?'Sending…':'Send reminders now'}</button></div>
    <div className="list-row static"><span className="grow"><strong>Send a test email</strong><small>Checks the Gmail connection. Send it to an inbox you can open.</small></span><input className="test-email" type="email" aria-label="Test email address" value={testTo} onChange={e=>setTestTo(e.target.value)} placeholder="you@gmail.com"/><button className="secondary" disabled={busy||!testTo} onClick={test}>Send test</button></div>
    {email.deliveries?.length>0&&<details><summary>Sent emails ({email.deliveries.length})</summary><div className="table-wrap"><table><thead><tr><th>To</th><th>Subject</th><th>Status</th><th>Time</th></tr></thead><tbody>{email.deliveries.map((d:any)=><tr key={d.id}><td>{d.recipient}</td><td>{d.subject}</td><td>{d.status}<small>{d.error}</small></td><td>{date(d.updated)}</td></tr>)}</tbody></table></div></details>}</>}
   {email&&!email.configured&&<details className="setup-steps"><summary>How to switch on email</summary><ol><li>Sign in to <b>archplazalab@gmail.com</b> and turn on <b>2-Step Verification</b> (Google Account → Security).</li><li>Open <b>App passwords</b>, create one named “ArchPlaza”, and copy the 16 letters.</li><li>Add it as <code>GMAIL_APP_PASSWORD</code> in the <code>.env</code> file (local) and in your hosting secrets (live site).</li><li>Restart the app.</li></ol></details>}
  </section>
  <details className="card"><summary>Audit history <span className="muted">({data.audit?.length||0} recent changes)</span></summary>{(data.audit||[]).map((a:any)=><div className="audit-row" key={a.id}><strong>{a.action}</strong><span>{a.actor} · {date(a.created)}</span></div>)}</details>
 </div>;}
