'use client';
import React,{useEffect,useRef,useState} from 'react';
import {UploadCloud,Check,X,AlertCircle,CheckCircle2,FileText} from 'lucide-react';

export const date=(v?:string)=>v?new Date(v).toLocaleString('en-GB',{timeZone:'Africa/Dar_es_Salaam',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'Not scheduled';
export const shortDate=(v:string)=>new Date(v).toLocaleString('en-GB',{timeZone:'Africa/Dar_es_Salaam',weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
export const remaining=(n:number)=>n<=0?'now':n<3600000?Math.ceil(n/60000)+' min':n<86400000?Math.ceil(n/3600000)+' hours':Math.ceil(n/86400000)+' days';
export const size=(b:number)=>b<1024*1024?Math.max(1,Math.round(b/1024))+' KB':(b/1024/1024).toFixed(1)+' MB';
export const dayParts=(v:string)=>{const d=new Date(Date.parse(v)+10800000);return {day:d.getUTCDate(),month:d.toLocaleString('en-GB',{month:'short',timeZone:'UTC'})};};

// Status colours: green = done/present, amber = late/due soon, red = overdue/absent, grey = excused/not started.
const tones:Record<string,string>={Present:'green',Submitted:'green',Marked:'green',Approved:'green',Released:'green',Verified:'green',Published:'green',Done:'green',Late:'amber','Due soon':'amber','Under review':'amber',Draft:'grey','Awaiting verification':'amber',Absent:'red',Overdue:'red',Declined:'red',Excused:'grey','Not started':'grey',Received:'blue','In progress':'blue','To do':'grey',Open:'blue'};
export function Badge({children,tone}:{children:React.ReactNode,tone?:string}){const t=tone??(typeof children==='string'?tones[children]:'')??'';return <span className={'badge '+(t||'')}>{children}</span>;}

// Planning motif: faint contour lines, used only behind headers and empty states.
export function Contours({className='contours'}:{className?:string}){return <svg className={className} viewBox="0 0 400 160" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="1">{[0,1,2,3,4,5,6].map(i=><path key={i} d={`M-20 ${150-i*18} C 60 ${120-i*22}, 120 ${170-i*20}, 200 ${110-i*18} S 330 ${60-i*14}, 420 ${100-i*20}`}/>)}<circle cx="318" cy="52" r="14"/><circle cx="318" cy="52" r="26"/><circle cx="318" cy="52" r="38"/></g></svg>;}

export function Empty({icon:Icon=FileText,title,body,action}:any){return <div className="empty"><Contours/><div className="empty-icon"><Icon size={22}/></div><h3>{title}</h3>{body&&<p>{body}</p>}{action}</div>;}

// Numbers count up briefly on first render; static when the viewer prefers reduced motion.
export function CountUp({value,decimals=0,suffix=''}:{value:number,decimals?:number,suffix?:string}){const [shown,setShown]=useState(value);const first=useRef(true);useEffect(()=>{if(!first.current||!Number.isFinite(value)){setShown(value);return;}first.current=false;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setShown(value);return;}let raf=0;const start=performance.now(),dur=700;const step=(t:number)=>{const p=Math.min(1,(t-start)/dur);setShown(value*(1-Math.pow(1-p,3)));if(p<1)raf=requestAnimationFrame(step);};raf=requestAnimationFrame(step);return()=>cancelAnimationFrame(raf);},[value]);return <>{shown.toFixed(decimals)}{suffix}</>;}

// Upload with real progress (fetch cannot report upload progress).
export function sendForm(url:string,form:FormData,onProgress?:(p:number)=>void){return new Promise<any>((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST',url);x.upload.onprogress=e=>{if(e.lengthComputable)onProgress?.(e.loaded/e.total);};x.onload=()=>{let d:any={};try{d=JSON.parse(x.responseText);}catch{}if(x.status>=200&&x.status<300)resolve(d);else reject(new Error(d.error||'Upload failed. Please try again.'));};x.onerror=()=>reject(new Error('Network error. Check your connection and try again.'));x.send(form);});}

export function UploadZone({accept,hint,multiple=true,files,setFiles}:{accept?:string,hint:string,multiple?:boolean,files:File[],setFiles:(f:File[])=>void}){const [over,setOver]=useState(false);const input=useRef<HTMLInputElement>(null);const add=(list:FileList|null)=>{if(!list)return;const next=multiple?[...files,...Array.from(list)]:Array.from(list).slice(0,1);setFiles(next.slice(0,12));};return <div className={'dropzone'+(over?' over':'')} onDragOver={e=>{e.preventDefault();setOver(true);}} onDragLeave={()=>setOver(false)} onDrop={e=>{e.preventDefault();setOver(false);add(e.dataTransfer.files);}}><button type="button" className="dropzone-target" onClick={()=>input.current?.click()}><UploadCloud size={28}/><strong>Drag files here or <u>browse</u></strong><span>{hint}</span></button><input ref={input} type="file" hidden accept={accept} multiple={multiple} onChange={e=>{add(e.target.files);e.target.value='';}}/>{files.length>0&&<ul className="file-list">{files.map((f,i)=><li key={i}><FileText size={16}/><span>{f.name}<small>{size(f.size)}</small></span><button type="button" className="icon-button small" aria-label={'Remove '+f.name} onClick={()=>setFiles(files.filter((_,j)=>j!==i))}><X size={14}/></button></li>)}</ul>}</div>;}

export function Progress({value,done}:{value:number,done?:boolean}){return <div className={'upload-progress'+(done?' done':'')} role="progressbar" aria-valuenow={Math.round(value*100)} aria-valuemin={0} aria-valuemax={100}><i style={{width:Math.round(value*100)+'%'}}/>{done&&<span className="tick"><Check size={14}/></span>}</div>;}

export type Toast={id:number,kind:'success'|'error',text:string};
export function Toasts({items,dismiss}:{items:Toast[],dismiss:(id:number)=>void}){return <div className="toasts" aria-live="polite">{items.map(t=><div key={t.id} className={'toast '+t.kind} role={t.kind==='error'?'alert':'status'}>{t.kind==='error'?<AlertCircle size={18}/>:<CheckCircle2 size={18}/>}<span>{t.text}</span><button className="icon-button small" aria-label="Dismiss" onClick={()=>dismiss(t.id)}><X size={14}/></button></div>)}</div>;}

export function Skeleton(){return <div className="app skeleton-app" aria-busy="true" aria-label="Loading your workspace"><aside className="sidebar"><div className="sk sk-logo"/>{Array.from({length:7}).map((_,i)=><div className="sk sk-nav" key={i}/>)}</aside><div className="main"><header className="topbar"><div className="sk sk-pill"/><div className="sk sk-avatar"/></header><main><div className="sk sk-title"/><div className="card-row">{[0,1,2].map(i=><div className="sk sk-card" key={i}/>)}</div><div className="sk sk-block"/></main></div></div>;}

// Focus the first field once when the dialog opens. The app re-renders every second (clocks and countdowns),
// so the keyboard handler reads the latest props through refs instead of re-running this effect.
export function Modal({title,onClose,busy,children,wide}:any){const ref=useRef<HTMLElement>(null);const latest=useRef({busy,onClose});latest.current={busy,onClose};useEffect(()=>{const el=ref.current?.querySelector('input:not([type=hidden]), textarea, select') as HTMLElement|null;el?.focus();},[]);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!latest.current.busy)latest.current.onClose();if(e.key==='Tab'&&ref.current){const items=Array.from(ref.current.querySelectorAll<HTMLElement>('button:not([disabled]), input, textarea, select, a[href]'));const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[]);return <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)onClose();}}><section ref={ref} className={'modal'+(wide?' wide':'')} role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-head"><h2 id="modal-title">{title}</h2><button className="icon-button" aria-label="Close dialog" disabled={busy} onClick={onClose}><X size={18}/></button></div>{children}</section></div>;}
