'use client';
import {useState} from 'react';
import {Upload,Download,FileSpreadsheet,CheckCircle2,FolderOpen} from 'lucide-react';
import {parseCSV} from '../../lib/imports';
export default function UploadCentre({records,preview,onRefresh,open}:any){const [kind,setKind]=useState('students'),[rows,setRows]=useState<any[]>([]),[filename,setFilename]=useState(''),[review,setReview]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[success,setSuccess]=useState('');
 async function read(file?:File){setReview(null);setRows([]);setSuccess('');setError('');if(!file)return;try{if(!file.name.toLowerCase().endsWith('.csv')||file.size>2*1024*1024)throw new Error('Choose a CSV file up to 2 MB. Export your Excel list as CSV first.');const parsed=parseCSV(await file.text());setFilename(file.name);setRows(parsed);}catch(e:any){setError(e.message);}}
 async function submit(commit=false){if(preview){setError('Sign in as a lecturer to preview and import your records.');return;}setBusy(true);setError('');try{const response=await fetch('/api/imports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({semester:new URLSearchParams(window.location.search).get('semester')||undefined,kind,rows,filename,preview:!commit})});const result:any=await response.json();if(!response.ok)throw new Error(result.error||result.errors?.join('\n'));if(commit){setSuccess(`${result.added} added · ${result.updated} updated`);setRows([]);setReview(null);await onRefresh();}else setReview(result);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <><div className="upload-options"><section className="panel"><div className="orange-icon"><FileSpreadsheet/></div><h2>Import teaching records</h2><p>Upload a student list or timetable. Review the rows before they change your live records.</p><div className="tabs"><button className={kind==='students'?'selected':''} onClick={()=>{setKind('students');setRows([]);setReview(null);}}>Class list</button><button className={kind==='timetable'?'selected':''} onClick={()=>{setKind('timetable');setRows([]);setReview(null);}}>Timetable</button></div><a className="template-link" href={'/templates/'+kind+'.csv'} download><Download size={16}/>Download {kind==='students'?'class-list':'timetable'} template</a><label className="upload-zone"><Upload size={30}/><strong>Choose a CSV file</strong><span>{kind==='students'?'Full name, registration number and (optional) programme':'Course, day, start, end, room and lecturers'}</span><input key={kind} type="file" accept=".csv,text/csv" onChange={e=>read(e.target.files?.[0])}/><small>Excel → Save as CSV · Up to 500 rows</small></label><p className="footnote">{kind==='students'?'Students create their own accounts by entering a registration number from this list and verifying their email. Re-importing updates names without unlinking anyone.':'Matching course, day and start time update an existing session. Other rows add sessions; existing unmatched sessions remain.'}</p></section><section className="panel"><div className="orange-icon"><FolderOpen/></div><h2>Upload course files</h2><p>Keep shapefile packages, lecture notes, timetable documents and supporting files in one place.</p><button className="primary" onClick={()=>open('resourceUpload',undefined,{category:'Document',course:'Both courses',published:false})}><Upload size={16}/>Upload files</button><div className="upload-help"><h3>Shapefile packages</h3><p>Zip matching .shp, .shx, .dbf and .prj files together. Add a clear title, coordinate system and source.</p><h3>Student records stay private</h3><p>Files labelled “Student roster” are visible only to lecturers. A timetable photo or PDF is stored as a reference; use the CSV template to import editable sessions.</p></div></section></div>
 {error&&<div className="error prewrap below">{error}</div>}{success&&<div className="notice below"><CheckCircle2/><strong>{success}</strong></div>}{rows.length>0&&<section className="panel below"><div className="section-heading"><div><h2>{filename}</h2><p>{rows.length} rows · showing the first 8</p></div><button className="secondary" disabled={busy} onClick={()=>submit(false)}>{busy?'Checking…':'Validate import'}</button></div><div className="table-wrap"><table><thead><tr>{Object.keys(rows[0]).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,8).map((r,i)=><tr key={i}>{Object.entries(r).map(([k,v])=><td key={k}>{String(v)}</td>)}</tr>)}</tbody></table></div>{review&&<div className="import-review"><CheckCircle2/><span>Ready: {review.added} new · {review.updated} updates</span><button className="primary" disabled={busy} onClick={()=>submit(true)}>Confirm import</button></div>}</section>}
 <div className="section-heading below"><h2>Import history</h2></div><div className="panel table-wrap"><table><thead><tr><th>File</th><th>Type</th><th>Result</th><th>Imported by</th></tr></thead><tbody>{records.filter((r:any)=>r.kind==='import').sort((a:any,b:any)=>b.created.localeCompare(a.created)).map((r:any)=><tr key={r.id}><td>{r.title}<small>{new Date(r.created).toLocaleString('en-GB',{timeZone:'Africa/Dar_es_Salaam'})}</small></td><td>{r.type}</td><td>{r.added} added · {r.updated} updated</td><td>{r.author}</td></tr>)}</tbody></table>{!records.some((r:any)=>r.kind==='import')&&<p className="inset">Your confirmed imports will appear here.</p>}</div></>;
}
