import {validateScheme,schemeSignature,courseworkMaximum} from '../../../lib/assessment-scheme';
import {hashPassword} from '../../../lib/auth-crypto';
import {activeSemester,writableSemester,inScope,enrolled,recordCourse,assertTargetWritable} from '../../../lib/academic';
import {actor,all,get,put,log,uid,now,db,visible,safeSession,belongs} from '../../../lib/lab';
import {emailConfigured,emailNotification} from '../../../lib/email';
const json=(x:any,status=200)=>Response.json(x,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req:Request){try{const portal=new URL(req.url).searchParams.get('portal');const u=await actor(portal!=='student');if(portal==='lecturer'&&u.role!=='admin')return json({error:'This account is enrolled as a student. Choose Student login. Lecturer access must be assigned by an administrator.',roleMismatch:true},403);const everything=await all();const params=new URL(req.url).searchParams;const semester=params.get('semester')||(await activeSemester())?.id;const accessible=everything.filter((r:any)=>r.kind==='enrollment'&&(u.role==='admin'||r.student===u.id));const semesters=everything.filter((r:any)=>r.kind==='semester'&&(u.role==='admin'||accessible.some((e:any)=>e.semester===r.id)));const courses=everything.filter((r:any)=>r.kind==='course'&&(u.role==='admin'||accessible.some((e:any)=>e.semester===semester&&e.course===r.code)));const selected=params.get('course')||courses[0]?.code||'';if(u.role!=='admin'&&selected&&!enrolled(everything,u.id,semester!,selected))throw new Error('Course access denied.');const records=everything.filter((r:any)=>r.kind==='profile'?u.role==='admin'||r.owner===u.id:inScope(r,everything,semester!,selected)&&(u.role==='admin'||!!selected));const peerIds=new Set(records.filter((r:any)=>r.kind==='group'&&(r.members||[]).includes(u.id)).flatMap((r:any)=>r.members));const roster=(await db().prepare('SELECT id,email,name,role,verified_at IS NOT NULL AS joined FROM users').all()).results;const students=u.role==='admin'?roster:roster.filter((s:any)=>peerIds.has(s.id)).map((s:any)=>({id:s.id,name:s.name}));const audit=u.role==='admin'?(await db().prepare('SELECT * FROM audit ORDER BY created DESC LIMIT 150').all()).results:[];const notificationReads=(await db().prepare('SELECT notification_id,read_revision FROM notification_reads WHERE user_id=?').bind(u.id).all()).results;return json({user:u,courses,semesters,semester,selectedCourse:selected,enrollments:accessible,pendingRoster:u.role==='admin'?everything.filter((r:any)=>r.kind==='roster'):[],records:records.filter((r:any)=>visible(r,u,records)).map((r:any)=>r.kind==='notification'?{...safeSession(r,u),read:notificationReads.some((n:any)=>n.notification_id===r.id&&n.read_revision>=r.revision)}:safeSession(r,u)),students,audit});}catch(e:any){return json({error:e.message},403);}}
const formats=['Assignment','Test / quiz file','Online quiz','Paper test','Report','Maps / images','Studio package','Quiz','Test'];
const letterStatuses=['Received','Under review','Approved','Declined'];
function required(d:any,keys:string[]){for(const k of keys)if(d[k]===undefined||d[k]==='')throw new Error(`${k} is required.`);}
function numeric(v:any,min:number,max:number,label:string){if(v===''||!Number.isFinite(Number(v))||Number(v)<min||Number(v)>max)throw new Error(`${label} must be between ${min} and ${max}.`);}
function validate(kind:string,d:any){
 if(['content','law','layer','group','notification'].includes(kind))required(d,['title']);
 if(kind==='assessment'&&(!d.course||!['Individual','Group'].includes(d.mode)||!formats.includes(d.type)))throw new Error('Choose a valid course, assessment type and participation mode.');
 if(kind==='assessment'&&d.type==='Online quiz'){if(!Array.isArray(d.questions)||!d.questions.length||d.questions.length>100)throw new Error('Add between 1 and 100 quiz questions.');d.questions=d.questions.map((q:any,i:number)=>{const text=String(q.text||'').trim();if(!text)throw new Error(`Question ${i+1} needs text.`);const points=Number(q.points||1);if(!(points>0&&points<=100))throw new Error(`Question ${i+1} needs 1–100 points.`);if(q.type==='mc'){const options=(q.options||[]).map((o:any)=>String(o).trim()).filter(Boolean);if(options.length<2||options.length>8)throw new Error(`Question ${i+1} needs 2–8 options.`);const answer=Number(q.answer);if(!(answer>=0&&answer<options.length))throw new Error(`Choose the correct option for question ${i+1}.`);return {id:String(q.id||crypto.randomUUID()),type:'mc',text,options,answer,points};}return {id:String(q.id||crypto.randomUUID()),type:'short',text,answer:String(q.answer||''),points};});numeric(d.timeLimit,1,300,'Time limit (minutes)');if(d.opens&&d.due&&Date.parse(d.opens)>=Date.parse(d.due))throw new Error('The quiz must open before it closes.');}
 if(kind==='material'){required(d,['title','course']);numeric(d.week,1,52,'Week');}
 if(kind==='timetable'){required(d,['course','day','start','end','room','lecturers']);if(!d.course||!['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].includes(d.day)||!/^\d{2}:\d{2}$/.test(d.start)||!/^\d{2}:\d{2}$/.test(d.end)||d.start>=d.end)throw new Error('Choose a valid course, day and end time after the start.');}
 if(kind==='assessment'){required(d,['title','course','type','mode']);numeric(d.max,1,10000,'Maximum mark');if(d.weight!=='')numeric(d.weight,0,courseworkMaximum(d.course),'Weight');numeric(d.penalty||0,0,100,'Penalty');if(d.published&&!d.due&&d.type!=='Online quiz')throw new Error('Set a deadline before publishing.');}
 if(kind==='settings'){numeric(d.weeks,1,52,'Semester weeks');}
 if(kind==='law'&&d.status==='Verified'&&(!d.source||!d.verifiedOn))throw new Error('A verified legal resource needs an official source and verification date.');
 for(const k of ['source','url'])if(d[k]&&!/^https?:\/\//.test(d[k]))throw new Error('Links must start with https:// or http://.');
 if(kind==='layer'){let g;try{g=JSON.parse(d.geojson);}catch{throw new Error('Enter valid GeoJSON.');}if(!['FeatureCollection','Feature'].includes(g.type))throw new Error('Use a GeoJSON Feature or FeatureCollection.');required(d,['title','city','source']);}
}
export async function POST(req:Request){try{
 if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return json({error:'Invalid origin.'},403);
 const u=await actor();const b:any=await req.json();if(b.expectUser&&b.expectUser!==u.id)return json({error:'You signed in as a different account in another tab. Reloading…',switched:true},409);const everything=await all();const term=await writableSemester(b.semester);const records=everything.filter((r:any)=>r.semester===term.id||['profile','course','enrollment'].includes(r.kind));const admin=u.role==='admin';let savedId='';let emailed:any=null;
 if(b.action==='assessmentScheme'){
  if(!admin)throw new Error('Lecturer access required.');
  if(!everything.some((r:any)=>r.kind==='course'&&r.code===b.course))throw new Error('Choose an existing course.');
  const assessments=records.filter((r:any)=>r.kind==='assessment'&&r.course===b.course&&r.published);
  const approved=b.approved===true,weights=validateScheme(assessments,b.weights,approved,b.course);
  const settings=records.find((r:any)=>r.kind==='settings');
  if(settings&&settings.revision!==b.settingsRevision)throw new Error('Settings changed. Refresh and try again.');
  const policy=String(b.policy||'').trim().slice(0,2000);
  const next={...(settings||{title:term.title,weeks:term.weeks,expectedStudents:0}),semester:term.id,schemes:{...(settings?.schemes||{}),[b.course]:{approved,policy,courseworkMaximum:courseworkMaximum(b.course),signature:schemeSignature(assessments.map((a:any)=>({...a,weight:weights.get(a.id)}))),confirmedAt:approved?now():null}}};
  const clean=(r:any)=>{const {id,kind,created,revision,data,...rest}=r;return rest;};
  const ops:any[]=[];
  const update=(id:string,revision:number,data:any)=>{
   ops.push(db().prepare('UPDATE records SET data=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(clean(data)),id,revision));
   // Force the whole transaction to roll back if any optimistic update lost a race.
   ops.push(db().prepare("INSERT INTO records(id,kind,data,revision,created) SELECT ?,'conflict','{}',1,? WHERE changes()=0").bind(id,now()));
  };
  for(const a of assessments)update(a.id,a.revision,{...a,weight:weights.get(a.id)});
  if(settings)update(settings.id,settings.revision,next);
  else ops.push(db().prepare('INSERT INTO records(id,kind,data,revision,created) VALUES(?,?,?,1,?)').bind('settings:'+term.id,'settings',JSON.stringify(clean(next)),now()));
  await db().batch(ops);
  await log(u.name,approved?'Confirmed assessment scheme':'Saved draft assessment scheme',b.course,null,{semester:term.id,approved,weights:Object.fromEntries(weights),policy});
  return json({ok:true});
 }
 if(b.action==='importRoster'){if(!admin)throw new Error('Lecturer access required.');if(!Array.isArray(b.rows)||b.rows.length>500)throw new Error('Supply up to 500 roster entries.');for(const r of b.rows){required(r,['name','registration']);}const statements=b.rows.map((r:any)=>db().prepare('INSERT OR IGNORE INTO records(id,kind,data,revision,created) VALUES(?,?,?,1,?)').bind('roster:'+String(r.registration).trim().toUpperCase(),'roster',JSON.stringify({name:String(r.name).trim(),registration:String(r.registration).trim(),programme:r.programme||'',status:'Waiting for student'}),now()));await db().batch(statements);return json({ok:true});}
 if(b.action==='linkRoster'){if(!admin)throw new Error('Lecturer access required.');const r=await get(b.id);if(!r||r.kind!=='roster'||r.student)throw new Error('Choose an unlinked roster entry.');const email=String(b.email||'').trim().toLowerCase();if(!/^[a-z0-9._%+-]+@gmail\.com$/i.test(email))throw new Error('Enter the student’s Gmail address.');if(await db().prepare('SELECT id FROM users WHERE email=?').bind(email).first())throw new Error('This email is already linked to an account.');const id=uid();await db().batch([db().prepare("INSERT INTO users(id,email,name,role) VALUES(?,?,?,'student')").bind(id,email,r.name),db().prepare('INSERT INTO records(id,kind,data,revision,created) VALUES(?,?,?,1,?)').bind('profile:'+id,'profile',JSON.stringify({owner:id,registration:r.registration,email,emailVerified:false,courses:[]}),now()),db().prepare('UPDATE records SET data=?,revision=revision+1 WHERE id=?').bind(JSON.stringify({...r,student:id,email,status:'Gmail linked'}),r.id)]);await log(u.name,'Linked roster Gmail',r.id,null,{student:id,email});return json({ok:true});}
 if(b.action==='archiveSemester'){if(!admin)throw new Error('Lecturer access required.');required(b,['title']);const id=uid();const semesters=await all('semester');if(semesters.some((s:any)=>s.id!==term.id&&!s.archived))throw new Error('Another semester is already active.');const archived={...term,archived:true,archivedAt:now()};const fresh={title:String(b.title).trim(),start:b.start||'',weeks:Number(b.weeks)||15,archived:false};await db().batch([db().prepare('UPDATE records SET data=?,revision=revision+1 WHERE id=?').bind(JSON.stringify(archived),term.id),db().prepare('INSERT INTO records(id,kind,data,revision,created) VALUES(?,?,?,1,?)').bind(id,'semester',JSON.stringify(fresh),now()),db().prepare('INSERT INTO records(id,kind,data,revision,created) VALUES(?,?,?,1,?)').bind('settings:'+id,'settings',JSON.stringify({semester:id,title:fresh.title,start:fresh.start,weeks:fresh.weeks,approved:false,expectedStudents:0,policy:'Configure the approved coursework scheme.'}),now())]);await log(u.name,'Archived semester',term.id,term,archived);return json({ok:true});}
 if(b.action==='course'){if(!admin)throw new Error('Lecturer access required.');required(b,['code','name']);const code=String(b.code).trim();if(everything.some((r:any)=>r.kind==='course'&&r.code===code))throw new Error('That course code already exists.');await put('course',uid(),{code,name:b.name,rooms:b.rooms||''});return json({ok:true});}
 if(b.action==='enrollCourse'){if(!admin)throw new Error('Lecturer access required.');if(!everything.some((r:any)=>r.kind==='course'&&r.code===b.course))throw new Error('Choose a course.');for(const student of b.students||[]){if(!await db().prepare("SELECT id FROM users WHERE id=? AND role='student'").bind(student).first())throw new Error('Choose an enrolled student.');const id=`enrollment:${term.id}:${b.course}:${student}`;if(!await get(id))await put('enrollment',id,{semester:term.id,course:b.course,student});}return json({ok:true});}
 if(b.action==='save'){
  if(!admin)throw new Error('Lecturer access required.');const kinds=['settings','timetable','assessment','group','notification','attendance','mark','submission','resource','material'];if(!kinds.includes(b.kind))throw new Error('Unsupported record.');
  const old=b.id?await get(b.id):null;if(old&&old.kind!==b.kind)throw new Error('Record type mismatch.');let d={...b.data,semester:term.id};if(['assessment','timetable','group','material'].includes(b.kind)&&!everything.some((r:any)=>r.kind==='course'&&r.code===d.course))throw new Error('Choose an existing course.');if(b.kind==='material'&&old)d={...old,...d,files:old.files||[]};if(b.kind==='assessment'&&old)d.files=old.files||[];if(b.kind==='resource'){if(!old)throw new Error('Upload a file before editing its resource.');d={...old,title:d.title,description:d.description,source:d.source,crs:d.crs,course:d.course,published:old.category==='Student roster'?false:!!d.published};}validate(b.kind,d);
  if(b.kind==='group'){d.members=Array.isArray(d.members)?d.members:[];const roster=(await db().prepare("SELECT id FROM users WHERE role = 'student'").all()).results; if(d.members.some((id:string)=>!roster.some((s:any)=>s.id===id)||!enrolled(everything,id,term.id,d.course)))throw new Error('Choose enrolled students.');}
  if(b.kind==='attendance'){if(!['Present','Late','Absent','Excused'].includes(d.status))throw new Error('Invalid attendance status.');if(!d.reason?.trim())throw new Error('A correction reason is required.');}
  if(b.kind==='mark'){const a=await get(d.assessment);if(!a||a.kind!=='assessment')throw new Error('Select an assessment.');const student=await db().prepare("SELECT id FROM users WHERE id = ? AND role = 'student'").bind(d.student||'').first();if(!student||!enrolled(everything,d.student,term.id,a.course))throw new Error('Select a student enrolled in this course.');numeric(d.score,0,Number(a.max),'Mark');numeric(d.penalty||0,0,100,'Penalty');if(d.waived&&!d.reason)throw new Error('Add the waiver reason.');}
  const id=old?.id||uid();savedId=id;await put(b.kind,id,d,old?b.revision:undefined);if(b.kind==='notification'&&d.email&&!old?.emailedAt){const saved=await get(id);emailed=await emailNotification(saved);await put('notification',id,{...saved,emailedAt:now(),emailResult:emailed},saved.revision);}if(b.kind==='settings')await put('semester',term.id,{...term,title:d.title,start:d.start,weeks:d.weeks},term.revision);await log(u.name,'Updated '+b.kind,id,old,d);
  if(b.kind==='timetable'||b.kind==='assessment'&&d.published||b.kind==='mark'&&d.released){await put('notification',uid(),{title:b.kind==='mark'?'Marks released':b.kind==='timetable'?'Timetable updated':`${d.type}: ${d.title}`,course:d.course||(b.kind==='mark'?(await get(d.assessment))?.course:undefined),body:b.kind==='timetable'?`${d.course} · ${d.day} ${d.start}–${d.end} · ${d.room}`:b.kind==='mark'?'Your assessment mark and feedback are available.':`${d.type==='Paper test'?'Test date':'Due'}: ${d.due?new Date(d.due).toLocaleString('en-GB',{timeZone:'Africa/Dar_es_Salaam',weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})+' (EAT)':'to be confirmed'}`,student:b.kind==='mark'?d.student:'',type:b.kind==='mark'?'Marks':b.kind==='timetable'?'Room / class change':'Deadline'});}
 }else if(b.action==='student'){
  if(!admin)throw new Error('Lecturer access required.');required(b,['name','email']);const name=String(b.name).trim().replace(/\s+/g,' ').slice(0,80),email=String(b.email).toLowerCase().trim(),role=b.role==='admin'?'admin':'student',registration=String(b.registration||'').trim().toUpperCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Enter a valid email.');if(role==='student'&&!registration)throw new Error('Enter the student’s registration number.');if(role==='admin'&&!/@(gmail|googlemail)\.com$/i.test(email))throw new Error('Lecturers sign in with Gmail. Enter their Gmail address.');
  if(await db().prepare('SELECT id FROM users WHERE email = ?').bind(email).first())throw new Error('That email already belongs to an account.');
  if(registration&&everything.some((r:any)=>r.kind==='profile'&&String(r.registration||'').toUpperCase()===registration))throw new Error('Another student already has this registration number.');
  const passwordHash=role==='admin'?await hashPassword(String(b.password||'')):null;
  const id=uid(),courses=everything.filter((r:any)=>r.kind==='course').map((r:any)=>r.code),roster=registration?await get('roster:'+registration):null;
  // A student added directly is also put on the class list and in every course, like a self-registered one.
  await db().batch([db().prepare('INSERT INTO users (id,email,name,role,password_hash) VALUES (?,?,?,?,?)').bind(id,email,name,role,passwordHash),...(role==='student'?[db().prepare('INSERT INTO records(id,kind,data,revision,created) VALUES(?,?,?,1,?)').bind('profile:'+id,'profile',JSON.stringify({owner:id,registration,email,emailVerified:false,courses}),now()),...(!roster?[db().prepare('INSERT INTO records(id,kind,data,revision,created) VALUES(?,?,?,1,?)').bind('roster:'+registration,'roster',JSON.stringify({name,registration,programme:'',status:'Waiting for student'}),now())]:[]),...courses.map((c:string)=>db().prepare('INSERT OR IGNORE INTO records(id,kind,data,revision,created) VALUES(?,?,?,1,?)').bind(`enrollment:${term.id}:${c}:${id}`,'enrollment',JSON.stringify({semester:term.id,course:c,student:id}),now()))]:[])]);
  await log(u.name,'Added '+role,id,null,{name,email,registration});
 }else if(b.action==='editStudent'){
  if(!admin)throw new Error('Lecturer access required.');const name=String(b.name||'').trim().replace(/\s+/g,' ').slice(0,80),registration=String(b.registration||'').trim().toUpperCase(),email=String(b.email||'').trim().toLowerCase();if(name.length<2)throw new Error('Enter the student’s name.');if(!registration)throw new Error('Enter the registration number.');if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Enter a valid email.');
  const s=b.id?await db().prepare('SELECT id,email,role,verified_at FROM users WHERE id = ?').bind(b.id).first():null;if(b.id&&(!s||s.role!=='student'))throw new Error('Student not found.');const roster=b.roster?await get(b.roster):null;if(b.roster&&(!roster||roster.kind!=='roster'))throw new Error('Class list entry not found.');
  const newRosterId='roster:'+registration;if(newRosterId!==roster?.id&&await get(newRosterId))throw new Error('Another class-list entry already uses this registration number.');
  if(s&&everything.some((r:any)=>r.kind==='profile'&&r.owner!==s.id&&String(r.registration||'').toUpperCase()===registration))throw new Error('Another student already has this registration number.');
  if(s&&email&&email!==s.email&&await db().prepare('SELECT id FROM users WHERE email = ? AND id != ?').bind(email,s.id).first())throw new Error('That email already belongs to another account.');
  const ops:any[]=[];
  if(roster){const {kind,id,revision,created,...rest}=roster;const data={...rest,name,registration};ops.push(newRosterId===roster.id?db().prepare('UPDATE records SET data=?,revision=revision+1 WHERE id=?').bind(JSON.stringify(data),roster.id):db().prepare('DELETE FROM records WHERE id = ?').bind(roster.id));if(newRosterId!==roster.id)ops.push(db().prepare('INSERT INTO records(id,kind,data,revision,created) VALUES(?,?,?,1,?)').bind(newRosterId,'roster',JSON.stringify(data),roster.created||now()));}
  if(s){if(s.verified_at)ops.push(db().prepare('INSERT INTO auth_claims(registration,user_id) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET registration=excluded.registration').bind(registration,s.id));ops.push(db().prepare('UPDATE users SET name = ?, email = ? WHERE id = ?').bind(name,email||s.email,s.id));const pr=everything.find((r:any)=>r.id==='profile:'+s.id);const {kind,id,revision,created,...rest}=pr||{};ops.push(db().prepare('INSERT INTO records(id,kind,data,revision,created) VALUES(?,?,?,1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,revision=records.revision+1').bind('profile:'+s.id,'profile',JSON.stringify({...rest,owner:s.id,registration,email:rest.email||email||s.email}),now()));}
  if(!ops.length)throw new Error('Choose a student.');await db().batch(ops);await log(u.name,'Edited student',s?.id||roster.id,{name:roster?.name,registration:roster?.registration},{name,registration,email});
 }else if(b.action==='autoGroups'){
  if(!admin)throw new Error('Lecturer access required.');numeric(b.size,2,20,'Group size');const students=(await db().prepare("SELECT id FROM users WHERE role = 'student' ORDER BY name").all()).results.filter((s:any)=>enrolled(everything,s.id,term.id,b.course)&&!records.some((g:any)=>g.kind==='group'&&g.course===b.course&&(g.members||[]).includes(s.id)));if(!students.length)throw new Error('All enrolled students are already assigned, or the roster is empty.');for(let i=students.length-1;i>0;i--){const j=crypto.getRandomValues(new Uint32Array(1))[0]%(i+1);[students[i],students[j]]=[students[j],students[i]];}for(let i=0;i<students.length;i+=Number(b.size)){const id=uid();const d={course:b.course,title:`Course group ${records.filter((r:any)=>r.kind==='group').length+Math.floor(i/b.size)+1}`,members:students.slice(i,i+Number(b.size)).map((s:any)=>s.id),description:'Shared course workspace'};await put('group',id,d);await log(u.name,'Created group',id,null,d);}
 }else if(b.action==='startSession'){
  if(!admin)throw new Error('Lecturer access required.');const t=await get(b.timetable);if(!t||t.kind!=='timetable')throw new Error('Choose a timetable session.');numeric(b.minutes,1,60,'Check-in duration');numeric(b.lateAfter,0,60,'Late threshold');const id=uid(),started=now();const code=String(100000+crypto.getRandomValues(new Uint32Array(1))[0]%900000);const d={title:t.course+' · '+t.room,course:t.course,timetable:t.id,started,expires:new Date(Date.now()+Number(b.minutes)*60000).toISOString(),lateAfter:Number(b.lateAfter),code,closed:false};await put('session',id,d);const students=(await db().prepare("SELECT id FROM users WHERE role = 'student'").all()).results.filter((s:any)=>enrolled(everything,s.id,term.id,t.course));for(const s of students)await put('attendance',`${id}:${s.id}`,{session:id,student:s.id,status:'Absent',time:'',reason:'Not checked in'});await log(u.name,'Started attendance',id,null,{...d,code:undefined});
 }else if(b.action==='closeSession'){
  if(!admin)throw new Error('Lecturer access required.');const s=await get(b.id);if(!s||s.kind!=='session')throw new Error('Session not found.');await put('session',s.id,{...s,closed:true},s.revision);await log(u.name,'Closed attendance',s.id,s,{closed:true});
 }else if(b.action==='checkin'){
  if(u.role!=='student')throw new Error('Student access required.');const s=records.find((r:any)=>r.kind==='session'&&r.code===String(b.code)&&!r.closed&&new Date(r.expires).getTime()>Date.now());if(s&&!enrolled(everything,u.id,term.id,s.course))throw new Error('You are not enrolled in this course.');if(!s)throw new Error('That code is invalid or the check-in window has closed.');const id=`${s.id}:${u.id}`,old=await get(id);if(old&&old.status!=='Absent')throw new Error('Your attendance is already recorded.');const d={session:s.id,student:u.id,status:Date.now()-Date.parse(s.started)>s.lateAfter*60000?'Late':'Present',time:now(),reason:'Session code check-in'};await put('attendance',id,d,old?.revision);await log(u.name,'Checked in',id,old,d);return json({ok:true,status:d.status});
 }else if(b.action==='task'||b.action==='map'){
  const g=b.group?await get(b.group):null;if(g&&g.kind!=='group')throw new Error('Invalid group.');if(g&&!admin&&!(g.members||[]).includes(u.id))throw new Error('Group access denied.');const old=b.id?await get(b.id):null;if(old&&(old.kind!==b.action||!admin&&!belongs(old,u,records)))throw new Error('Access denied.');required(b.data,['title']);const d={...b.data,owner:old?.owner||u.id,group:old?.group||g?.id||'',author:u.name};await put(b.action,old?.id||uid(),d,old?.revision);if(g)await put('activity',uid(),{owner:u.id,group:g.id,title:`${u.name} ${old?'updated':'added'} ${b.action}: ${d.title}`});
 }else if(b.action==='profile'){
  const profile=await get('profile:'+u.id),f=b.data||{},text=(v:any,max:number)=>String(v??'').trim().slice(0,max);const name=text(f.name,80);if(name.length<2)throw new Error('Enter your full name.');const phone=text(f.phone,20);if(phone&&!/^\+?[0-9 ()-]{7,20}$/.test(phone))throw new Error('Enter a valid phone number, e.g. +255 712 345 678.');const notifications:any={};for(const key of ['classes','deadlines','marks','roomChanges','announcements'])notifications[key]=f.notifications?.[key]!==false;
  const next={...(profile||{}),owner:u.id,email:profile?.email||u.email,courses:profile?.courses||[],programme:text(f.programme,80),year:text(f.year,20),phone,notifications,registration:profile?.registration||text(f.registration,30)};
  await put('profile','profile:'+u.id,next,profile?.revision);if(name!==u.name)await db().prepare('UPDATE users SET name = ? WHERE id = ?').bind(name,u.id).run();await log(u.name,'Updated profile','profile:'+u.id,profile,next);
 }else if(b.action==='letterReply'){
  if(!admin)throw new Error('Lecturer access required.');const l=await get(b.id);if(!l||l.kind!=='letter')throw new Error('Letter not found.');if(!letterStatuses.includes(b.status))throw new Error('Choose a valid status.');const reply=String(b.reply||'').trim().slice(0,2000);if(b.status==='Declined'&&!reply)throw new Error('Add a short reply explaining the decision.');
  if(b.excuse){if(b.status!=='Approved')throw new Error('Only approved letters can excuse an absence.');const a=await get(b.excuse);if(!a||a.kind!=='attendance'||a.student!==l.owner)throw new Error('Choose one of this student’s attendance records.');const d={...a,status:'Excused',reason:'Approved letter: '+l.subject};await put('attendance',a.id,d,a.revision);await log(u.name,'Updated attendance',a.id,a,d);}
  const d={...l,status:b.status,reply,repliedBy:u.name,replied:now(),excused:b.excuse||l.excused||''};await put('letter',l.id,d,l.revision);await log(u.name,'Replied to letter',l.id,l,d);await put('notification',uid(),{title:`Your ${l.type.toLowerCase()}: ${b.status}`,body:reply||`Your letter “${l.subject}” is ${b.status.toLowerCase()}.`,student:l.owner,type:'Announcement',course:l.course||''});
 }else if(b.action==='releaseMarks'){
  if(!admin)throw new Error('Lecturer access required.');const a=await get(b.id);if(!a||a.kind!=='assessment')throw new Error('Assessment not found.');const released=!!b.released;for(const m of records.filter((r:any)=>r.kind==='mark'&&r.assessment===a.id)){await put('mark',m.id,{...m,released},m.revision);if(released&&!m.released)await put('notification',uid(),{title:'Marks released',body:`Your mark and feedback for ${a.title} are available.`,student:m.student,type:'Marks',course:a.course});}await put('assessment',a.id,{...a,marksReleased:released},a.revision);await log(u.name,released?'Released marks':'Withheld marks',a.id,null,{released});
 }else if(b.action==='quizStart'||b.action==='quizSubmit'){
  if(u.role!=='student')throw new Error('Only students can take quizzes.');const a=await get(b.id);if(!a||a.kind!=='assessment'||!a.published||a.type!=='Online quiz')throw new Error('This quiz is not available.');if(!enrolled(everything,u.id,term.id,a.course))throw new Error('You are not enrolled in this course.');const id=`attempt:${a.id}:${u.id}`,attempt=await get(id),t=Date.now();
  if(b.action==='quizStart'){if(attempt)return json({ok:true,started:attempt.started});if(a.opens&&t<Date.parse(a.opens))throw new Error('This quiz has not opened yet.');if(a.due&&t>Date.parse(a.due))throw new Error('This quiz has closed.');const started=now();await put('attempt',id,{owner:u.id,assessment:a.id,course:a.course,started,submitted:''});return json({ok:true,started});}
  if(!attempt)throw new Error('Start the quiz first.');if(attempt.submitted)throw new Error('You have already submitted this quiz.');const limit=Math.min(Date.parse(attempt.started)+Number(a.timeLimit)*60000,a.due?Date.parse(a.due):Infinity);const late=t>limit+60000;const answers:any={};let auto=0,total=0,review=false;for(const q of a.questions){total+=q.points;const v=b.answers?.[q.id];if(q.type==='mc'){answers[q.id]=Number.isInteger(v)?v:null;if(!late&&v===q.answer)auto+=q.points;}else{answers[q.id]=String(v??'').slice(0,4000);review=true;}}
  await put('attempt',id,{...attempt,answers,submitted:now(),late,autoPoints:auto,totalPoints:total,needsReview:review},attempt.revision);const markId=`mark:${a.id}:${u.id}`,score=Math.round(auto/total*Number(a.max)*10)/10;if(!await get(markId))await put('mark',markId,{student:u.id,assessment:a.id,score,penalty:0,waived:false,reason:late?'Submitted after the time limit':'',feedback:review?'Short answers awaiting lecturer review.':'',released:false,auto:true});await log(u.name,'Submitted quiz',id,null,{late,auto,total});
 }else if(b.action==='deleteNotification'||b.action==='deleteGroup'){
  if(!admin)throw new Error('Lecturer access required.');const kind=b.action==='deleteGroup'?'group':'notification';const r=await get(b.id);if(!r||r.kind!==kind)throw new Error('Not found.');
  // A group's tasks and activity go with it; submitted work and files stay in the record.
  await db().batch([db().prepare('DELETE FROM records WHERE id = ?').bind(r.id),...(kind==='group'?[db().prepare("DELETE FROM records WHERE kind IN ('task','activity','map') AND json_extract(data,'$.group') = ?").bind(r.id)]:[])]);await log(u.name,'Deleted '+kind,r.id,r,null);
 }else if(b.action==='deleteStudent'){
  if(!admin)throw new Error('Lecturer access required.');const sid=String(b.id||''),rosterId=String(b.roster||'');const s=sid?await db().prepare('SELECT id,name,email,role FROM users WHERE id = ?').bind(sid).first():null;
  if(sid&&(!s||s.role!=='student'))throw new Error('Only student accounts can be removed here.');const roster=rosterId?await get(rosterId):null;if(rosterId&&(!roster||roster.kind!=='roster'))throw new Error('Class list entry not found.');if(!s&&!roster)throw new Error('Choose a student.');
  const ops:any[]=[];
  if(s){
   // Personal records go with the account; shared group work stays.
   ops.push(db().prepare("DELETE FROM records WHERE kind IN ('enrollment','attendance','mark','attempt','letter') AND (json_extract(data,'$.student') = ? OR json_extract(data,'$.owner') = ?)").bind(s.id,s.id),db().prepare('DELETE FROM records WHERE id = ?').bind('profile:'+s.id),db().prepare('DELETE FROM users WHERE id = ?').bind(s.id));
   for(const g of everything.filter((r:any)=>r.kind==='group'&&(r.members||[]).includes(s.id)))ops.push(db().prepare('UPDATE records SET data=json_set(data,\'$.members\',json(?)),revision=revision+1 WHERE id=?').bind(JSON.stringify(g.members.filter((m:string)=>m!==s.id)),g.id));
   for(const r of everything.filter((r:any)=>r.kind==='roster'&&r.student===s.id&&r.id!==rosterId)){const {student,email,enteredName,linked,kind,id,revision,created,...rest}=r;ops.push(db().prepare('UPDATE records SET data=?,revision=revision+1 WHERE id=?').bind(JSON.stringify({...rest,status:'Waiting for student'}),r.id));}
  }
  const unlink=(r:any)=>{const {student,email,enteredName,linked,kind,id,revision,created,...rest}=r;return db().prepare('UPDATE records SET data=?,revision=revision+1 WHERE id=?').bind(JSON.stringify({...rest,status:'Waiting for student'}),r.id);};
  if(roster)ops.push(b.removeFromList?db().prepare('DELETE FROM records WHERE id = ?').bind(roster.id):unlink(roster));
  await db().batch(ops);if(s)try{await (await import('../../../lib/lab')).bucket().delete('avatars/'+s.id);}catch{}
  await log(u.name,b.removeFromList?'Removed student from class list':'Removed student account',sid||rosterId,{name:s?.name||roster?.name,email:s?.email},null);
 }else if(b.action==='deleteMaterial'){
  if(!admin)throw new Error('Lecturer access required.');const m=await get(b.id);if(!m||m.kind!=='material')throw new Error('Material not found.');await assertTargetWritable(m);await db().prepare('DELETE FROM records WHERE id = ?').bind(m.id).run();await log(u.name,'Removed material',m.id,m,null);
 }else throw new Error('Unknown action.');return json({ok:true,id:savedId||undefined,emailed:emailed||undefined});
 }catch(e:any){console.error('Lab action',e);return json({error:e.message||'Unable to save. Please try again.'},400);}}
