export type ImportRow = Record<string,string>;
export function parseCSV(input:string):ImportRow[]{
 const rows:string[][]=[];let row:string[]=[],value='',quoted=false;const text=input.replace(/^\uFEFF/,'');
 for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else if(!value||quoted)quoted=!quoted;else throw new Error('Unexpected quote in CSV.');}else if(c===','&&!quoted){row.push(value.trim());value='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value.trim());if(row.some(Boolean))rows.push(row);row=[];value='';}else value+=c;}
 if(quoted)throw new Error('CSV contains an unclosed quoted field.');row.push(value.trim());if(row.some(Boolean))rows.push(row);if(rows.length<2)throw new Error('Include column headings and at least one data row.');const header=rows.shift()!.map(h=>h.toLowerCase().replace(/\s+/g,'_'));if(new Set(header).size!==header.length)throw new Error('CSV column headings must be unique.');return rows.map((r,i)=>{if(r.length!==header.length)throw new Error(`Row ${i+2}: expected ${header.length} columns, found ${r.length}.`);return Object.fromEntries(header.map((h,j)=>[h,r[j]]));});
}
export const validEmail=(s:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)&&s.length<=254;
export const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
export function validateImport(kind:string,rows:ImportRow[],courses:string[]=[]){const errors:string[]=[];const seen=new Set<string>();if(!['students','timetable'].includes(kind))throw new Error('Choose students or timetable.');if(!Array.isArray(rows)||!rows.length||rows.length>500)throw new Error('Import between 1 and 500 rows.');rows.forEach((r,i)=>{const fail=(m:string)=>errors.push(`Row ${i+2}: ${m}`);if(kind==='students'){if(!r.name?.trim())fail('full name is required');const reg=(r.registration||'').trim().toUpperCase();if(!reg)fail('registration number is required');if(reg.startsWith('REPLACE'))fail('replace the template row with a real student');if(seen.has(reg))fail('duplicate registration number in this file');seen.add(reg);}else{if(!courses.includes(r.course))fail('use an existing course code');if(!DAYS.includes(r.day))fail('use a full day name');const time=/^(?:[01]\d|2[0-3]):[0-5]\d$/;if(!time.test(r.start||'')||!time.test(r.end||'')||r.start>=r.end)fail('use valid HH:MM times with end after start');if(!r.room?.trim()||!r.lecturers?.trim())fail('room and lecturers are required');const key=[r.course,r.day,r.start].join('|');if(seen.has(key))fail('duplicate session in this file');seen.add(key);}});return errors;}
